### PR TITLE
Regenerate fonts

### PR DESCRIPTION
**Pull request by rettinghaus**
This PR's only purpose is to remove and re-generate all SMuFL glyphs with the updated script.

### CODE REVIEW

**Comment by rettinghaus** [comment]
There seems to be something off with cutouts now.

**Comment by lpugin** [comment]
Something goes wrong when building the test suite

**Comment by rettinghaus** [comment]
Yes, but I guess that's not my fault:
```shell
E: Unable to locate package openresolv
E: Unable to locate package wireguard
```

**Comment by lpugin** [comment]
Please try to make a new PR.

**Pull request closed without merging**
