### PR TITLE
Fix for beam stems length 

### LINKED ISSUE #2779: Stem length + 32nd  note beam interaction
In the following example, bottom staff, the 32nd note beam is touching the notehead:

Screen Shot 2022-04-06 at 7 36 16 AM

<details>
<summary>
Click to view MEI data for above example
</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title>Piano Sonata No. 4 in E-flat major</title>
   </titleStmt>
   <pubStmt>
    <respStmt>
     <persName xml:id="persname-L39" analog="humdrum:EED" role="editor">Craig Stuart Sapp</persName>
    </respStmt>
    <date xml:id="date-L36" analog="humdrum:YER">2018</date>
    <availability>
     <useRestrict xml:id="userestrict-L33" analog="humdrum:YEC">2018 Craig Stuart Sapp</useRestrict>
     <useRestrict xml:id="userestrict-L35" analog="humdrum:YEM">Licence: (CC BY-NC-SA 4.0) https://creativecommons.org/licenses/by-nc-sa/4.0</useRestrict>
    </availability>
   </pubStmt>
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2022-04-06T07:34:28" version="3.10.0-dev-4a1d799">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
   <projectDesc>
    <p>Encoded by: Craig Stuart Sapp</p>
    <p>Version: 2018/06/16</p>
   </projectDesc>
  </encodingDesc>
  <workList>
   <work>
    <title xml:id="title-L4" analog="humdrum:OTL" type="main">Piano Sonata No. 4 in E-flat major</title>
    <composer analog="humdrum:COM" xml:id="person-L1">Mozart, Wolfgang Amadeus</composer>
    <creation>
     <date analog="humdrum:ODT">1774///</date>
    </creation>
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mkghl23">
    <score xml:id="s6jnhod">
     <scoreDef xml:id="sfum83i" midi.bpm="120.000000">
      <pgHead xml:id="pezfxl6">
       <rend xml:id="rrtzp8l" halign="center" valign="middle">
        <rend xml:id="rm0aiyw" fontsize="large">Piano Sonata No. 4 in E-flat major</rend>
        <lb xml:id="lghpcwh" /> 
<lb xml:id="l9pj09z" /> </rend>
       <rend xml:id="rmcenpu" halign="right" valign="bottom" fontsize="small">Wolfgang Amadeus Mozart</rend>
       <rend xml:id="r6kfmfp" halign="right" valign="bottom" fontsize="small">1756–91</rend>
      </pgHead>
      <staffGrp xml:id="s3uu0o" bar.thru="true" symbol="brace">
       <staffDef xml:id="s86wifv" n="1" lines="5">
        <clef xml:id="clef-L11F2" shape="G" line="2" />
        <keySig xml:id="keysig-L12F2" accid="f" pname="e" mode="major" sig="3f" />
        <meterSig xml:id="metersig-L14F2" count="3" unit="4" />
       </staffDef>
       <staffDef xml:id="sgr6vyp" n="2" lines="5">
        <clef xml:id="clef-L11F1" shape="F" line="4" />
        <keySig xml:id="keysig-L12F1" accid="f" pname="e" mode="major" sig="3f" />
        <meterSig xml:id="metersig-L14F1" count="3" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L10F1">
      <measure xml:id="measure-L1" n="47">
       <staff xml:id="sl3i4e5" n="1">
        <layer xml:id="layer-L10F2N1" n="1">
         <beam xml:id="beam-L18F3-L20F3">
          <note xml:id="note-L18F3" dur="32" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L19F3" dur="32" oct="5" pname="e" accid.ges="f" />
          <note xml:id="note-L20F3" dots="1" dur="8" oct="5" pname="f" accid.ges="n" />
         </beam>
         <rest xml:id="rest-L21F3" dur="4" />
         <beam xml:id="beam-L22F3-L25F3">
          <note xml:id="note-L22F3" dur="16" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L23F3" dur="16" oct="5" pname="e" accid.ges="f" />
          <note xml:id="note-L24F3" dur="16" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L25F3" dur="16" oct="5" pname="c" accid.ges="n" />
         </beam>
        </layer>
       </staff>
       <staff xml:id="sisuohg" n="2">
        <layer xml:id="layer-L10F1N1" n="1">
         <beam xml:id="beam-L18F1-L20F1">
          <note xml:id="note-L18F1" dur="32" oct="3" pname="b" accid.ges="f" />
          <note xml:id="note-L19F1" dur="32" oct="4" pname="c" accid.ges="n" />
          <note xml:id="note-L20F1" dots="1" dur="8" oct="4" pname="d" accid.ges="n" />
         </beam>
         <rest xml:id="rest-L21F1" dur="4" ploc="d" oloc="3" />
         <beam xml:id="beam-L22F1-L25F1">
          <note xml:id="note-L22F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L23F1" dur="16" oct="4" pname="c" accid.ges="n" />
          <note xml:id="note-L24F1" dur="16" oct="3" pname="b" accid.ges="f" />
          <note xml:id="note-L25F1" dur="16" oct="3" pname="a" accid="n" />
         </beam>
        </layer>
        <layer xml:id="layer-L11F1N2" n="2">
         <note xml:id="note-L18F2" dur="4" oct="3" pname="f" accid.ges="n" />
         <rest xml:id="rest-L21F2" dur="4" ploc="d" oloc="3" />
         <note xml:id="note-L22F2" dur="4" oct="3" pname="f" accid.ges="n" />
        </layer>
       </staff>
       <dynam xml:id="dynam-L18F4" staff="1" tstamp="1.000000" vgrp="100">f</dynam>
       <slur xml:id="slur-L18F3-L20F3" staff="1" startid="#note-L18F3" endid="#note-L20F3" />
       <dynam xml:id="dynam-L22F4" staff="1" tstamp="3.000000" vgrp="100">p</dynam>
       <slur xml:id="slur-L22F3-L25F3" staff="1" startid="#note-L22F3" tstamp2="4"/>
       <slur xml:id="slur-L18F1-L20F1" staff="2" startid="#note-L18F1" endid="#note-L20F1" />
       <slur xml:id="slur-L22F1-L25F1" staff="2" startid="#note-L22F1" endid="#note-L25F1" />
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

I am wondering if there might be a problem with a sign for adjustment amount for such cases, since the stem length adjustment on the beam on the same beat in the top staff is longer than the manually typeset version:

Screen Shot 2022-04-06 at 7 40 21 AM

### PR DESCRIPTION
**Pull request by Monceber**
closes #2779

image

### CODE REVIEW

**Comment by craigsapp** [comment]
Looks good, although stems pointing away from the staff are traditionally shortened, so the first beam on the bottom staff now looks too high and would benefit by being dropped down two diatonic steps (one staff-line space) for an optimal stem length.  Here are how beamless note stems behave in verovio (notice the first stem is longer than the last one):

Screen Shot 2022-04-20 at 8 10 50 AM

<details>
<summary>
Click to view MEI data for above example
</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2022-04-20T08:10:44" version="3.10.0-dev-67ca6d0-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="m7ymosk">
    <score xml:id="sp9ckvl">
     <scoreDef xml:id="sxdwrll">
      <staffGrp xml:id="s8n5dpr">
       <staffDef xml:id="srjwgk6" n="1" lines="5">
        <clef xml:id="c18fz5t" shape="G" line="2" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1">
       <staff xml:id="sf1vcph" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L2F1" type="placed" dur="4" oct="4" pname="b" stem.dir="up" accid.ges="n" />
         <note xml:id="note-L3F1" type="placed" dur="4" oct="5" pname="c" stem.dir="up" accid.ges="n" />
         <note xml:id="note-L4F1" type="placed" dur="4" oct="5" pname="d" stem.dir="up" accid.ges="n" />
         <note xml:id="note-L5F1" type="placed" dur="4" oct="5" pname="e" stem.dir="up" accid.ges="n" />
         <note xml:id="note-L6F1" type="placed" dur="4" oct="5" pname="f" stem.dir="up" accid.ges="n" />
         <note xml:id="note-L7F1" type="placed" dur="4" oct="5" pname="g" stem.dir="up" accid.ges="n" />
         <note xml:id="note-L8F1" type="placed" dur="4" oct="5" pname="a" stem.dir="up" accid.ges="n" />
         <note xml:id="note-L9F1" type="placed" dur="4" oct="5" pname="b" stem.dir="up" accid.ges="n" />
         <note xml:id="note-L10F1" type="placed" dur="4" oct="6" pname="c" stem.dir="up" accid.ges="n" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

**Comment by Monceber** [comment]
Yes, that's one of the points that needs to be further improved eventually. Currently we calculate stem length based on the duration of the note and it's position on the staff (so that notes outside of the staff are shortened). However, in a beam this poses a problem, especially in cases where several durations are present within. If stem length of the longest note is taken then original issue occurs - additional beam overlap with notes. If shortest note length taken instead (like in this solution), then stem length might seem to be over the top.
One way to solve this could be taking average of all durations and calculating stem length based on that, but it might lead to some other problems like beams not touching staff lines or overlaps in cases with a wider range of notes.

**Comment by rettinghaus** [comment]
Also note that this follows Gould, p. 19: 

> Beams should never be closer to the notehead than the correct position of the semiquaver beam (2½ spaces).

**Comment by craigsapp** [comment]
2.5 spaces seems a little confusing on page 19:

Screen Shot 2022-04-20 at 11 40 45 AM

It seems that 2.5 means from the center of the notehead to the top of the first beam, which is otherwise 2 staff spaces (4 diatonic steps) to the bottom of the beam:

Screen Shot 2022-04-20 at 11 51 52 AM

**Comment by craigsapp** [comment]
For enhancement of beam placement, this book is good to study:

The Art of Music Engraving and Processing
by Ted Ross
published by Hansen Press: Miami, 1970

page 122: default placement of 16th note repeated notes:

Screen Shot 2022-04-20 at 12 05 01 PM

Some rules for two 16th notes going up a step (page 123):

Screen Shot 2022-04-20 at 12 07 52 PM

Rules for triple beams (page 125):

Screen Shot 2022-04-20 at 12 10 20 PM

There are also tables of nominal placements of the first beam based on the starting note (before any fix for steep beams, etc.).  Here are the ones for D's on the treble clef on page 105:

Screen Shot 2022-04-20 at 12 15 01 PM

**Comment by lpugin** [comment]
Let me merge it already. It can still be improved further as suggested above.

**Comment by craigsapp** [comment]
> Let me merge it already. It can still be improved further as suggested above.

Yes, the above notes are intended for future enhancements, not for doing anything more on the PR.

**Pull request merged**
