### PR TITLE
Humdrum import: Handle clef changes in the middle of a rest

### PR DESCRIPTION
**Pull request by gregchapman-dev**
Clef change in the middle of a space was already handled. In the case of a (visible) rest, we need to keep the visual duration of the original rest, set it's gestural duration to the pre-clef duration, and add a space after the clef containing the remainder of the duration (i.e. the post-clef duration).

### CODE REVIEW

**Comment by gregchapman-dev** [comment]
@craigsapp Here's my first cut.  I was going to support "clef in the middle of a note/chord" as well, but I really think that's just not a valid thing to do (plus more complicated to implement).

**Comment by gregchapman-dev** [comment]
Noticed right at the end (and fixed) the fact that splitting of invisible rests (and now visible rests, too) was happening backward.  The first rest had the second rest's duration, and vice versa.  Now to run thousands of tests.

**Comment by gregchapman-dev** [comment]
Much testing later, this looks pretty good.  Please review.

**Comment by lpugin** [comment]
@craigsapp I am about to overtake your dictatorial control over this.

**Comment by craigsapp** [comment]
> @craigsapp I am about to overtake your dictatorial control over this.

The Oberdictator has spoken :-)

This might be a good time to create some Humdrum &rarr; MEI regression tests.  Then if all of the regression test pass, that would be the main approval system.

**Comment by craigsapp** [comment]
Here is a test case for this PR that is now working:

```tsv
!!!OPR: Clef
!!!ONM: 17
!!!OTL: Clef change splitting rest
**kern	**kern
*clefF4	*clefG2
*M4/4	*M4/4
1C	1c
2r	4e
.	8BL
*clefG2	*
.	8g<J
=	=
1c	1c
==	==
*-	*-
!!!RDF**kern: < = below
```

Screen Shot 2022-12-26 at 4 31 08 PM

<details>
<summary> Click to view MEI conversion for above Humdrum data </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title>Clef change splitting rest</title>
         </titleStmt>
         <pubStmt />
      </fileDesc>
      <encodingDesc>
         <appInfo>
            <application isodate="2022-12-26T16:32:05" version="3.15.0-dev-6acd06e">
               <name>Verovio</name>
               <p>Transcoded from Humdrum</p>
            </application>
         </appInfo>
      </encodingDesc>
      <workList>
         <work>
            <title xml:id="title-L3" analog="humdrum:OTL" type="main">Clef change splitting rest</title>
         </work>
      </workList>
      <extMeta>
         <frames xmlns="http://www.humdrum.org/ns/humxml">
            <metaFrame n="0" token="!!!OPR: Clef" xml:id="L1">
               <frameInfo>
                  <startTime float="0" />
                  <frameType>reference</frameType>
                  <referenceKey>OPR</referenceKey>
                  <referenceValue>Clef</referenceValue>
               </frameInfo>
            </metaFrame>
            <metaFrame n="1" token="!!!ONM: 17" xml:id="L2">
               <frameInfo>
                  <startTime float="0" />
                  <frameType>reference</frameType>
                  <referenceKey>ONM</referenceKey>
                  <referenceValue>17</referenceValue>
               </frameInfo>
            </metaFrame>
            <metaFrame n="2" token="!!!OTL: Clef change splitting rest" xml:id="L3">
               <frameInfo>
                  <startTime float="0" />
                  <frameType>reference</frameType>
                  <referenceKey>OTL</referenceKey>
                  <referenceValue>Clef change splitting rest</referenceValue>
               </frameInfo>
            </metaFrame>
            <metaFrame n="15" token="!!!RDF**kern: &lt; = below" xml:id="L16">
               <frameInfo>
                  <startTime float="10" />
                  <frameType>reference</frameType>
                  <referenceKey>RDF**kern</referenceKey>
                  <referenceValue>&lt; = below</referenceValue>
               </frameInfo>
            </metaFrame>
         </frames>
      </extMeta>
   </meiHead>
   <music>
      <body>
         <mdiv xml:id="mhu2q9r">
            <score xml:id="s1izumqx">
               <scoreDef xml:id="smcmgfw">
                  <pgHead xml:id="p1e5wz0n">
                     <rend xml:id="r20ebpc" halign="center" valign="middle">
                        <rend xml:id="r1iqa8y5" fontsize="large">Clef change splitting rest</rend>
                        <lb xml:id="ldrjr7e" /> 
<lb xml:id="l1vtyrpo" /> </rend>
                  </pgHead>
                  <staffGrp xml:id="s1ugyzkq" bar.thru="true" symbol="brace">
                     <staffDef xml:id="staffdef-L4F2" n="1" lines="5">
                        <clef xml:id="clef-L5F2" shape="G" line="2" />
                        <meterSig xml:id="metersig-L6F2" count="4" unit="4" />
                     </staffDef>
                     <staffDef xml:id="staffdef-L4F1" n="2" lines="5">
                        <clef xml:id="clef-L5F1" shape="F" line="4" />
                        <meterSig xml:id="metersig-L6F1" count="4" unit="4" />
                     </staffDef>
                  </staffGrp>
               </scoreDef>
               <section xml:id="section-L4F1">
                  <measure xml:id="measure-L1">
                     <staff xml:id="staff-L4F2" n="1">
                        <layer xml:id="layer-L1F2N1" n="1">
                           <note xml:id="note-L7F2" dur="1" oct="4" pname="c" accid.ges="n" />
                           <note xml:id="note-L8F2" dur="4" oct="4" pname="e" accid.ges="n" />
                           <beam xml:id="beam-L9F2-L11F2">
                              <note xml:id="note-L9F2" dur="8" oct="3" pname="b" accid.ges="n" />
                              <note xml:id="note-L11F2" dur="8" staff="2" oct="4" pname="g" stem.dir="up" accid.ges="n" />
                           </beam>
                        </layer>
                     </staff>
                     <staff xml:id="staff-L4F1" n="2">
                        <layer xml:id="layer-L1F1N1" n="1">
                           <note xml:id="note-L7F1" dur="1" oct="3" pname="c" accid.ges="n" />
                           <rest xml:id="rest-L8F1" dur.ges="4" dots.ges="1" dur="2" />
                           <clef xml:id="clef-L10F1" shape="G" line="2" />
                           <space xml:id="space-L8F1b" dur="8" />
                        </layer>
                     </staff>
                  </measure>
                  <measure xml:id="measure-L12" right="end">
                     <staff xml:id="staff-L12F2N1" n="1">
                        <layer xml:id="layer-L12F2N1" n="1">
                           <note xml:id="note-L13F2" dur="1" oct="4" pname="c" accid.ges="n" />
                        </layer>
                     </staff>
                     <staff xml:id="staff-L12F1N1" n="2">
                        <layer xml:id="layer-L12F1N1" n="1">
                           <note xml:id="note-L13F1" dur="1" oct="4" pname="c" accid.ges="n" />
                        </layer>
                     </staff>
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```

</details>

The half-note rest is split into a visible and invisible portion:

```xml
<rest xml:id="rest-L8F1" dur.ges="4" dots.ges="1" dur="2" />
<clef xml:id="clef-L10F1" shape="G" line="2" />
<space xml:id="space-L8F1b" dur="8" />
```

**Pull request merged**
