### PR TITLE
Control slur endpoint flexibility and symmetry

### LINKED ISSUE #2731: slur refinement (vertical adjustment to flatten slur)
In the following example, there is undesired curvature and asymetry related to avoiding the accidental on the second note of the beam group:
Screen Shot 2022-03-22 at 10 55 32 PM

<details>
<summary>
Click to view MEI data for above example
</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2022-03-22T22:55:20" version="3.10.0-dev-fe12a79-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="m9yw3in">
    <score xml:id="sqydlrv">
     <scoreDef xml:id="s59asjl">
      <staffGrp xml:id="sa26bn5" bar.thru="true" symbol="brace">
       <staffDef xml:id="spxjhmu" n="1" lines="5">
        <clef xml:id="clef-L2F2" shape="G" line="2" />
        <keySig xml:id="keysig-L3F2" accid="f" pname="b" mode="major" sig="2f" />
        <meterSig xml:id="metersig-L5F2" count="2" unit="4" />
       </staffDef>
       <staffDef xml:id="s5qj82r" n="2" lines="5">
        <clef xml:id="clef-L2F1" shape="F" line="4" />
        <keySig xml:id="keysig-L3F1" accid="f" pname="b" mode="major" sig="2f" />
        <meterSig xml:id="metersig-L5F1" count="2" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="69">
       <staff xml:id="svzljkj" n="1">
        <layer xml:id="layer-L1F2N1" n="1">
         <beam xml:id="beam-L8F2-L11F2">
          <note xml:id="note-L8F2" type="placed" dur="16" oct="4" pname="d" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L9F2" type="placed" dur="16" oct="3" pname="a" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L10F2" type="placed" dur="16" oct="3" pname="b" stem.dir="up" accid.ges="f" />
          <note xml:id="note-L11F2" type="placed" dur="16" oct="4" pname="d" stem.dir="up" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L12F2-L15F2">
          <note xml:id="note-L12F2" type="placed" dur="16" oct="4" pname="e" stem.dir="up" accid.ges="f" />
          <note xml:id="note-L13F2" type="placed" dur="16" oct="3" pname="a" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L14F2" type="placed" dur="16" oct="3" pname="b" stem.dir="up" accid.ges="f" />
          <note xml:id="note-L15F2" type="placed" dur="16" oct="4" pname="e" stem.dir="up" accid.ges="f" />
         </beam>
        </layer>
       </staff>
       <staff xml:id="s45mrca" n="2">
        <layer xml:id="layer-L1F1N1" n="1">
         <beam xml:id="beam-L8F1-L10F1">
          <note xml:id="note-L8F1" type="placed" dur="8" oct="2" pname="a" stem.dir="down" accid="f" />
          <note xml:id="note-L10F1" type="placed" dur="8" oct="3" pname="a" stem.dir="down" accid="f" />
         </beam>
         <beam xml:id="beam-L12F1-L14F1">
          <note xml:id="note-L12F1" type="placed" dur="8" oct="2" pname="g" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L14F1" type="placed" dur="8" oct="3" pname="g" stem.dir="down" accid.ges="n" />
         </beam>
        </layer>
       </staff>
       <dir xml:id="dir-L8F3" staff="1" tstamp="1.000000">cresc. poco a poco</dir>
       <slur xml:id="slur-L8F1-L14F1" staff="2" startid="#note-L8F1" endid="#note-L14F1" />
      </measure>
      <measure xml:id="measure-L16" n="70">
       <staff xml:id="staff-L16F2N1" n="1">
        <layer xml:id="layer-L16F2N1" n="1">
         <beam xml:id="beam-L17F2-L20F2">
          <note xml:id="note-L17F2" type="placed" dur="16" oct="4" pname="e" stem.dir="up" accid="n" />
          <note xml:id="note-L18F2" type="placed" dur="16" oct="3" pname="a" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L19F2" type="placed" dur="16" oct="3" pname="b" stem.dir="up" accid.ges="f" />
          <note xml:id="note-L20F2" type="placed" dur="16" oct="4" pname="e" stem.dir="up" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L21F2-L24F2">
          <note xml:id="note-L21F2" type="placed" dur="16" oct="4" pname="f" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L22F2" type="placed" dur="16" oct="3" pname="a" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L23F2" type="placed" dur="16" oct="3" pname="b" stem.dir="up" accid.ges="f" />
          <note xml:id="note-L24F2" type="placed" dur="16" oct="4" pname="f" stem.dir="up" accid.ges="n" />
         </beam>
        </layer>
       </staff>
       <staff xml:id="staff-L16F1N1" n="2">
        <layer xml:id="layer-L16F1N1" n="1">
         <beam xml:id="beam-L17F1-L19F1">
          <note xml:id="note-L17F1" type="placed" dur="8" oct="2" pname="g" stem.dir="down" accid="f" />
          <note xml:id="note-L19F1" type="placed" dur="8" oct="3" pname="g" stem.dir="down" accid="f" />
         </beam>
         <beam xml:id="beam-L21F1-L23F1">
          <note xml:id="note-L21F1" type="placed" dur="8" oct="2" pname="f" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L23F1" type="placed" dur="8" oct="3" pname="f" stem.dir="down" accid.ges="n" />
         </beam>
        </layer>
       </staff>
       <slur xml:id="slur-L17F1-L23F1" staff="2" startid="#note-L17F1" endid="#note-L23F1" />
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

Here is a better target rendering:

Screen Shot 2022-03-22 at 10 56 01 PM

where the slurs are (or nearly are) horizontal in order to avoid the large curvature.  Instead of literally placing the slur start just above the starting notes, it is moved upwards to avoid the exaggerated curvature that would be caused by avoiding the second note of the slur.

Notice that symmetric slurs as in the target rendering are less distracting and therefore more readable (this could be used to generate some sort of preference rule to decide on raising the vertical placement for the start of the slur).  Also notice that reducing the curvature of the slurs will allow the staves to be more tightly spaced as in the example target rendering.

### PR DESCRIPTION
**Pull request by DavidBauer1984**
This PR adds two options regarding slur adjustment:

1. `--slur-endpoint-flexibility` controls how much endpoints are allowed to move during adjustment. Its range is between 0 and 1. The default is zero which corresponds to previous behaviour.
2. `--slur-symmetry` controls how much symmetry is enforced during adjustment. Its range is also between 0 and 1 with default zero corresponding to previous behaviour.

This closes #2731 and addresses some ideas that came up in the discussion of #2819 . 

When playing around with these parameters I would recommend to trade more symmetry against increased endpoint flexibility, i.e. choosing similar values for both parameters. 

_Default values_
For now I kept the default at (0, 0), since these values correspond to the previous behaviour and as such have been extensively tested. We might adapt this in the future, but this requires more testing and just because (0.5, 0.5) is in the middle doesn't mean that it is the best default.

_Examples_
| Endpoint flexibility | Symmetry | Rendering |
| -------- | ------ | --------- |
| 0.0 | 0.0 | Flex0-Sym0 |
| 0.5 | 0.5 | Flex05-Sym05 |
| 1.0 | 1.0 | Flex1-Sym1 |
| 0.0 | 1.0 | Flex0-Sym1 |
| 1.0 | 0.0 | Flex1-Sym0 |

### CODE REVIEW

**Comment by craigsapp** [comment]
I will point out that the (0.0, 1.0) example is not symmetric (discussed in some previous issues):

Screen Shot 2022-05-19 at 6 00 56 AM

This is symmetric:

Screen Shot 2022-05-19 at 6 00 34 AM

Where the midpoint in the slur creates a perpendicular line at the midpoint between the two endpoints:

Screen Shot 2022-05-19 at 6 06 02 AM

Here is my layout preference for these slurs:

Screen Shot 2022-05-19 at 6 12 10 AM

**Comment by DavidBauer1984** [comment]
> I like (1.0, 1.0) the best, of course.

I knew that you would say that 😄 I guess the discussion which values are best will be controversial and is partly a matter of taste. Here is an example (first system of Chopin ballad) where smaller values produce better results, at least in my opinion:
| Values | Rendering |
| ------ | --------- |
| (1.0,1.0) |  |
| (0.5,0.5) |  |
| (0.0,0.0) |  |

> I will point out that the (0.0, 1.0) example is not symmetric (discussed in some previous issues):

Yes and there is no guarantee when setting `--slur-symmetry` to 1.0 that all slurs will be totally symmetric. Instead this deactivates certain features during slur adjustment that usually lead to asymmetric (but flatter) slurs.

> A problem with this musical example is that there is another tunable parameter that should be added: the top of the flat accidental in particular is usually granted a typesetting rule exception and is allowed to touch slurs.

Yes, we are aware of this problem and have some ongoing work regarding this. It's a different issue which needs to be addressed in a different PR.

**Comment by lpugin** [comment]
Could the two examples be added to the test suite? I will add some documentation about the options using them.

**Comment by DavidBauer1984** [comment]
Sure, the first example is contained in #2731 . The second example is here:
<details>
<summary>Show MEI</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title />
            <respStmt />
         </titleStmt>
         <pubStmt><date isodate="2021-07-30" type="encoding-date">2021-07-30</date>
         </pubStmt>
      </fileDesc>
      <encodingDesc xml:id="encodingdesc-xwopln">
         <appInfo xml:id="appinfo-a209u3">
            <application xml:id="application-oqlg5f" isodate="2021-10-07T15:48:50" version="3.7.0-dev-ab9a2ad">
               <name xml:id="name-54q3e8">Verovio</name>
               <p xml:id="p-9bogng">Transcoded from MusicXML</p>
            </application>
         </appInfo>
      </encodingDesc>
   </meiHead>
   <music>
      <body>
         <mdiv xml:id="mlj4v68">
            <score xml:id="sdie2kd">
               <scoreDef xml:id="sqosio4">
                  <staffGrp xml:id="s2kukk6">
                     <staffGrp xml:id="S1-ty9q8jPDVsCWNSEmZ4EMBA" bar.thru="true">
                        <staffDef xml:id="sbx4ten" n="1" lines="5" ppq="4">
                           <clef xml:id="clef-1" shape="G" line="2" />
                           <keySig xml:id="key-1" sig="2f" />
                           <meterSig xml:id="time-1" count="4" sym="common" unit="4" />
                        </staffDef>
                        <staffDef xml:id="spk2jp7" n="2" lines="5" ppq="4">
                           <clef xml:id="clef-2" shape="F" line="4" />
                           <keySig xml:id="key-2" sig="2f" />
                           <meterSig xml:id="time-2" count="4" sym="common" unit="4" />
                        </staffDef>
                        <grpSym xml:id="gn2ijqh" symbol="brace" />
                     </staffGrp>
                  </staffGrp>
               </scoreDef>
               <section xml:id="svuhz75">
                  <pb xml:id="py6q87o" />
                  <measure xml:id="measure-0006-9490-9920-1-mdiv-1" n="1">
                     <staff xml:id="sz84vl2" n="1">
                        <layer xml:id="li53gq4" n="5">
                           <note xml:id="note-0006-9690-10240-1" dur.ppq="8" dur="2" staff="2" oct="3" pname="c" stem.dir="up" />
                           <beam xml:id="bbp348n">
                              <note xml:id="note-0006-9800-10240-1" dur.ppq="2" dur="8" staff="2" oct="3" pname="c" stem.dir="up" />
                              <note xml:id="note-0006-9850-10230-1" dur.ppq="2" dur="8" staff="2" oct="3" pname="e" stem.dir="up" accid.ges="f" />
                              <note xml:id="note-0006-9910-10200-1" dur.ppq="2" dur="8" staff="2" oct="3" pname="a" stem.dir="up">
                                 <accid xml:id="ab6knci" accid="f" accid.ges="f" />
                              </note>
                              <note xml:id="note-0006-9960-10190-1" dur.ppq="2" dur="8" staff="2" oct="3" pname="b" stem.dir="up" accid.ges="f" />
                           </beam>
                        </layer>
                     </staff>
                     <staff xml:id="sj8roo" n="2">
                        <layer xml:id="lnf0fbc" n="6">
                           <note xml:id="note-0006-9690-10300-2" dur.ppq="8" dur="2" oct="2" pname="c" stem.dir="down" />
                           <beam xml:id="b8vh1h4">
                              <note xml:id="note-0006-9800-10300-2" dur.ppq="2" dur="8" oct="2" pname="c" stem.dir="down" />
                              <note xml:id="note-0006-9850-10290-2" dur.ppq="2" dur="8" oct="2" pname="e" stem.dir="down" accid.ges="f" />
                              <note xml:id="note-0006-9910-10260-2" dur.ppq="2" dur="8" oct="2" pname="a" stem.dir="down">
                                 <accid xml:id="a2gjz0s" accid="f" accid.ges="f" />
                              </note>
                              <note xml:id="note-0006-9960-10250-2" dur.ppq="2" dur="8" oct="2" pname="b" stem.dir="down" accid.ges="f">
                                 <artic xml:id="aqllcdt" artic="stacciss" place="below" />
                              </note>
                           </beam>
                        </layer>
                     </staff>
                     <tempo xml:id="taastha" place="above" staff="1" tstamp="1.000000" xml:lang="it" midi.bpm="40.000000">Largo</tempo>
                     <slur xml:id="bow-0006-10260-10040" startid="#note-0006-9690-10240-1" endid="#note-0006-10820-10000-1" curvedir="above" />
                     <slur xml:id="bow-0006-9750-10220" startid="#note-0006-9690-10240-1" endid="#note-0006-9800-10240-1" curvedir="above" />
                     <slur xml:id="bow-0006-9740-10320" startid="#note-0006-9690-10300-2" endid="#note-0006-9800-10300-2" curvedir="below" />
                     <dynam xml:id="dtvbbdu" place="below" staff="1" tstamp="1.000000" vgrp="50">f</dynam>
                     <dir xml:id="dl2z3ho" place="below" staff="1" tstamp="3.000000" vgrp="50">pesante</dir>
                  </measure>
                  <measure xml:id="measure-0006-10000-9920-1-mdiv-1" n="2">
                     <staff xml:id="scpiukl" n="1">
                        <layer xml:id="l2dk81g" n="1">
                           <beam xml:id="bq36t3k">
                              <note xml:id="note-0006-10040-10090-1" dur.ppq="2" dur="8" oct="4" pname="c" stem.dir="up" />
                              <note xml:id="note-0006-10100-10100-1" dur.ppq="2" dur="8" oct="3" pname="a" stem.dir="up">
                                 <accid xml:id="a8nrd53" accid="f" accid.ges="f" />
                              </note>
                              <note xml:id="note-0006-10160-10070-1" dur.ppq="2" dur="8" oct="4" pname="e" stem.dir="up" accid.ges="f" />
                              <note xml:id="note-0006-10210-10030-1" dur.ppq="2" dur="8" oct="4" pname="b" stem.dir="up" accid.ges="f" />
                           </beam>
                           <beam xml:id="bu66vcl">
                              <note xml:id="note-0006-10260-10030-1" dur.ppq="2" dur="8" oct="5" pname="c" stem.dir="up" />
                              <note xml:id="note-0006-10320-10040-1" dur.ppq="2" dur="8" oct="4" pname="a" stem.dir="up">
                                 <accid xml:id="aath33a" accid="f" accid.ges="f" />
                              </note>
                              <note xml:id="note-0006-10370-10010-1" dur.ppq="2" dur="8" oct="5" pname="e" stem.dir="up" accid.ges="f" />
                              <note xml:id="note-0006-10430-9970-1" dur.ppq="2" dur="8" oct="5" pname="b" stem.dir="up" accid.ges="f" />
                           </beam>
                        </layer>
                     </staff>
                     <staff xml:id="sa19wg1" n="2">
                        <layer xml:id="lpt4na" n="5">
                           <beam xml:id="b9jn0xp">
                              <note xml:id="note-0006-10040-10240-2" dur.ppq="2" dur="8" oct="3" pname="c" stem.dir="down" />
                              <note xml:id="note-0006-10100-10260-2" dur.ppq="2" dur="8" oct="2" pname="a" stem.dir="down">
                                 <accid xml:id="a4i050x" accid="f" accid.ges="f" />
                              </note>
                              <note xml:id="note-0006-10160-10230-2" dur.ppq="2" dur="8" oct="3" pname="e" stem.dir="down" accid.ges="f" />
                              <note xml:id="note-0006-10210-10190-2" dur.ppq="2" dur="8" oct="3" pname="b" stem.dir="down" accid.ges="f" />
                           </beam>
                           <beam xml:id="bun5d44">
                              <note xml:id="note-0006-10260-10180-2" dur.ppq="2" dur="8" oct="4" pname="c" stem.dir="down" />
                              <note xml:id="note-0006-10320-10200-2" dur.ppq="2" dur="8" oct="3" pname="a" stem.dir="down">
                                 <accid xml:id="ayjd4zd" accid="f" accid.ges="f" />
                              </note>
                              <note xml:id="note-0006-10370-10070-2" dur.ppq="2" dur="8" staff="1" oct="4" pname="e" stem.dir="down" accid.ges="f" />
                              <note xml:id="note-0006-10430-10040-2" dur.ppq="2" dur="8" staff="1" oct="4" pname="b" stem.dir="down" accid.ges="f" />
                           </beam>
                        </layer>
                     </staff>
                  </measure>
                  <measure xml:id="measure-0006-10470-9920-1-mdiv-1" n="3">
                     <staff xml:id="sky4578" n="1">
                        <layer xml:id="lqfy6fo" n="1">
                           <beam xml:id="bnajbal">
                              <note xml:id="note-0006-10510-9970-1" dur.ppq="2" dur="8" oct="6" pname="c" stem.dir="up" />
                              <note xml:id="note-0006-10570-9990-1" dur.ppq="2" dur="8" oct="5" pname="g" stem.dir="up" />
                              <note xml:id="note-0006-10620-9970-1" dur.ppq="2" dur="8" oct="5" pname="b" stem.dir="up" accid.ges="f" />
                              <note xml:id="note-0006-10680-9980-1" dur.ppq="2" dur="8" oct="5" pname="a" stem.dir="up">
                                 <accid xml:id="aw86clt" accid="f" accid.ges="f" />
                              </note>
                           </beam>
                           <note xml:id="note-0006-10730-9990-1" dur.ppq="4" dur="4" oct="5" pname="g" stem.dir="up" />
                           <note xml:id="note-0006-10820-10000-1" dur.ppq="2" dur="8" oct="5" pname="f" stem.dir="up">
                              <accid xml:id="ai9xbs5" accid="s" accid.ges="s" />
                           </note>
                           <rest xml:id="rest-0006-10890-9990" dur.ppq="2" dur="8" />
                        </layer>
                        <layer xml:id="lyqupfu" n="2">
                           <beam xml:id="btis4n4">
                              <note xml:id="note-0006-10510-10030-2" dur.ppq="2" dur="8" oct="5" pname="c" stem.dir="down" />
                              <note xml:id="note-0006-10570-10050-2" dur.ppq="2" dur="8" oct="4" pname="g" stem.dir="down" />
                              <note xml:id="note-0006-10620-10040-2" dur.ppq="2" dur="8" oct="4" pname="b" stem.dir="down" accid.ges="f" />
                              <note xml:id="note-0006-10680-10040-2" dur.ppq="2" dur="8" oct="4" pname="a" stem.dir="down">
                                 <accid xml:id="a3p1kdb" accid="f" accid.ges="f" />
                              </note>
                           </beam>
                           <note xml:id="note-0006-10730-10050-2" dur.ppq="4" dur="4" oct="4" pname="g" stem.dir="down" />
                           <note xml:id="note-0006-10820-10060-2" dur.ppq="2" dur="8" oct="4" pname="f" stem.dir="down">
                              <accid xml:id="anjr5ta" accid="s" accid.ges="s" />
                           </note>
                           <rest xml:id="rest-0006-10890-10090" dur.ppq="2" dur="8" />
                        </layer>
                     </staff>
                     <staff xml:id="s2c47t1" n="2">
                        <layer xml:id="lt4kvmx" n="1">
                           <mSpace xml:id="mvps1p2" />
                        </layer>
                     </staff>
                     <dynam xml:id="dcexbz9" place="below" staff="1" tstamp="1.000000" vgrp="70">dim. </dynam>
                     <hairpin xml:id="wedge-0006-10690-10140" staff="1" tstamp="1.000000" tstamp2="0m+3.5000" form="dim" opening="3.000000vu" place="below" vgrp="70" />
                  </measure>
                  <scoreDef xml:id="sptjpdw" ppq="12" />
                  <measure xml:id="measure-0006-10920-9920-1-mdiv-1" n="4">
                     <staff xml:id="smeo765" n="1">
                        <layer xml:id="l66xogn" n="1">
                           <rest xml:id="rest-0006-10970-10000" dur.ppq="6" dur="8" />
                           <beam xml:id="b5y3b6j">
                              <note xml:id="note-0006-11020-10000-1" dur.ppq="6" dur="8" oct="5" pname="f" stem.dir="up">
                                 <accid xml:id="aj5czzk" accid="s" accid.ges="s" />
                              </note>
                              <note xml:id="note-0006-11080-9990-1" dur.ppq="6" dur="8" oct="5" pname="g" stem.dir="up" />
                              <note xml:id="note-0006-11130-10000-1" dur.ppq="6" dur="8" oct="5" pname="f" stem.dir="up" accid.ges="s" />
                           </beam>
                           <beam xml:id="bxnc57c">
                              <note xml:id="note-0006-11200-10010-1" dur.ppq="6" dur="8" oct="5" pname="e" stem.dir="up">
                                 <accid xml:id="aei9m6a" accid="s" accid.ges="s" />
                              </note>
                              <note xml:id="note-0006-11250-10000-1" dur.ppq="6" dur="8" oct="5" pname="f" stem.dir="up" accid.ges="s" />
                              <tuplet xml:id="t242cse" num="3" numbase="2" num.format="count">
                                 <note xml:id="note-0006-11310-9980-1" dur.ppq="4" dur="8" oct="5" pname="a" stem.dir="up" />
                                 <note xml:id="note-0006-11350-9990-1" dur.ppq="4" dur="8" oct="5" pname="g" stem.dir="up" />
                                 <note xml:id="note-0006-11410-10010-1" dur.ppq="4" dur="8" oct="5" pname="e" stem.dir="up">
                                    <accid xml:id="atda2ki" accid="f" accid.ges="f" />
                                 </note>
                              </tuplet>
                           </beam>
                        </layer>
                        <layer xml:id="l918kyg" n="2">
                           <rest xml:id="rest-0006-10970-10090" dur.ppq="6" dur="8" />
                           <beam xml:id="b6um1et">
                              <note xml:id="note-0006-11020-10060-2" dur.ppq="6" dur="8" oct="4" pname="f" stem.dir="down">
                                 <accid xml:id="ao000hf" accid="s" accid.ges="s" />
                              </note>
                              <note xml:id="note-0006-11080-10050-2" dur.ppq="6" dur="8" oct="4" pname="g" stem.dir="down" />
                              <note xml:id="note-0006-11130-10060-2" dur.ppq="6" dur="8" oct="4" pname="f" stem.dir="down" accid.ges="s" />
                           </beam>
                           <beam xml:id="bxzkb0z">
                              <note xml:id="note-0006-11200-10070-2" dur.ppq="6" dur="8" oct="4" pname="e" stem.dir="down">
                                 <accid xml:id="atv1o2" accid="s" accid.ges="s" />
                              </note>
                              <note xml:id="note-0006-11250-10060-2" dur.ppq="6" dur="8" oct="4" pname="f" stem.dir="down" accid.ges="s" />
                              <tuplet xml:id="tnyc743" num="3" numbase="2" num.format="count">
                                 <note xml:id="note-0006-11310-10040-2" dur.ppq="4" dur="8" oct="4" pname="a" stem.dir="down" />
                                 <note xml:id="note-0006-11350-10050-2" dur.ppq="4" dur="8" oct="4" pname="g" stem.dir="down" />
                                 <note xml:id="note-0006-11410-10070-2" dur.ppq="4" dur="8" oct="4" pname="e" stem.dir="down">
                                    <accid xml:id="au169oh" accid="f" accid.ges="f" />
                                 </note>
                              </tuplet>
                           </beam>
                        </layer>
                     </staff>
                     <staff xml:id="sxj0z3a" n="2">
                        <layer xml:id="lxeiuob" n="1">
                           <mSpace xml:id="mirlpnw" />
                        </layer>
                     </staff>
                     <slur xml:id="bow-0006-11240-9910" startid="#note-0006-11020-10000-1" endid="#note-0006-9780-10530-1" curvedir="above" />
                     <dynam xml:id="dcjbijv" place="below" staff="1" tstamp="1.500000" vgrp="70">p</dynam>
                  </measure>
                  <sb xml:id="soc7olw" />
                  <measure xml:id="measure-0006-9390-10430-1-mdiv-1" n="5">
                     <staff xml:id="s5ct5vt" n="1">
                        <layer xml:id="l2zhs5m" n="1">
                           <beam xml:id="b1ep557">
                              <note xml:id="note-0006-9540-10520-1" dots="1" dur.ppq="9" dur="8" oct="5" pname="e" stem.dir="up" accid.ges="f" />
                              <note xml:id="note-0006-9610-10530-1" dur.ppq="3" dur="16" oct="5" pname="d" stem.dir="up" />
                              <tuplet xml:id="tbu72g6" num="3" numbase="2" num.format="count">
                                 <note xml:id="note-0006-9660-10510-1" dur.ppq="4" dur="8" oct="5" pname="f" stem.dir="up">
                                    <accid xml:id="afb2k59" accid="n" accid.ges="n" />
                                 </note>
                                 <note xml:id="note-0006-9700-10520-1" dur.ppq="4" dur="8" oct="5" pname="e" stem.dir="up" accid.ges="f" />
                                 <note xml:id="note-0006-9740-10530-1" dur.ppq="4" dur="8" oct="5" pname="d" stem.dir="up" />
                              </tuplet>
                           </beam>
                           <note xml:id="note-0006-9780-10530-1" dur.ppq="12" dur="4" oct="5" pname="d" stem.dir="up" />
                           <rest xml:id="rest-0006-9870-10520" dur.ppq="12" dur="4" />
                        </layer>
                        <layer xml:id="lnlup3j" n="2">
                           <beam xml:id="bk1p1ik">
                              <note xml:id="note-0006-9540-10580-2" dots="1" dur.ppq="9" dur="8" oct="4" pname="e" stem.dir="down" accid.ges="f" />
                              <note xml:id="note-0006-9610-10590-2" dur.ppq="3" dur="16" oct="4" pname="d" stem.dir="down" />
                              <note xml:id="note-0006-9660-10570-2" dur.ppq="6" dur="8" oct="4" pname="f" stem.dir="down">
                                 <accid xml:id="abj8azp" accid="n" accid.ges="n" />
                              </note>
                              <note xml:id="note-0006-9700-10580-2" dur.ppq="6" dur="8" oct="4" pname="e" stem.dir="down" accid.ges="f" />
                              <note xml:id="note-0006-9740-10590-2" dur.ppq="6" dur="8" oct="4" pname="d" stem.dir="down" />
                           </beam>
                           <note xml:id="note-0006-9790-10590-2" dur.ppq="12" dur="4" oct="4" pname="d" stem.dir="down" />
                           <rest xml:id="rest-0006-9870-10620" dur.ppq="12" dur="4" />
                        </layer>
                     </staff>
                     <staff xml:id="sjdkb0l" n="2">
                        <layer xml:id="lilyncg" n="1">
                           <mSpace xml:id="muc3sc6" />
                        </layer>
                     </staff>
                  </measure>
                </section>
             </score>
          </mdiv>
      </body>
   </music>
</mei>
```
</details>

**Comment by DavidBauer1984** [comment]
> It would be interesting to see your (0.0, 1.0) example.

It's almost the same as (0.0, 0.0) here. The difference in the rendering above mostly stems from the change in endpoint flexibility. The reason is that for very long slurs asymmetries are still allowed even with `--slur-symmetry` set to 1.0.

Please understand this option in the sense that it is trying to prevent asymmetries. In a previous post you described the possibilities as:
> Maybe such a parameter would indicate how hard you want the layout algorithm to preserve symmetry, and there would be a categorical set of about three possibilities: "always", "strongly", "weakly".

In this sense `--slur-symmetry = 0` should correspond to "weak" and `--slur-symmetry = 1` should correspond to "strong".

**Pull request merged**
