### PR TITLE
Further improvement of the nested alignment

### PR DESCRIPTION
**Pull request by lpugin**
Before and after

* unison-001
image

image

* tuplet-017
image
image

* layer-002
image

### CODE REVIEW

**Comment by lpugin** [comment]
This change yields highly optimised layout, maybe too much in some cases. We can make it an option `--layer-compact-layout` (any ideas?) for it to be enabled explicitly.

This would be the default:
image


With `--layer-compact-layout`:
image

Any thoughts?

**Comment by GBogdahn** [comment]
I think this looks very promising!

**Comment by rettinghaus** [comment]
I would prefer the other way round, i.e. have a `--relaxed-spacing` option for a less-than-optimal spacing.

**Comment by lpugin** [comment]
Latest change ensures there is a standard spacing between notes. This addresses #2261. See examples added there

**Comment by rettinghaus** [comment]
Looking at `slur-002` this seems to fix #2259 too.

**Comment by lpugin** [comment]
> Looking at `slur-002` this seems to fix #2259 too.

I doubt it. Probably just because the slur change hasn't be merge into this branch.

**Comment by rettinghaus** [comment]
@lpugin to what exactly applies now `leftMarginAccid`? Decreasing the default value below 1 will lead to several collisions.

**Comment by lpugin** [comment]
> @lpugin to what exactly applies now `leftMarginAccid`? Decreasing the default value below 1 will lead to several collisions.

I can look. Would it be possible to have some examples of the collisions you get when changing the values?

**Pull request merged**
