### PR TITLE
Add github action for clang-format check

### PR DESCRIPTION
**Pull request by rettinghaus**

### CODE REVIEW

**Comment by lpugin** [comment]
Aren't we going to have problems if a contributors runs a different version of clang-format that produces slightly different results?

**Comment by rettinghaus** [comment]
I think, what could make problems is using clang-format version prior to 9. That's why we say we use version 10: https://book.verovio.org/contributing/guidelines.html
Anyway, it doesn't block merging, it just shows potential formatting problems.

**Comment by rettinghaus** [comment]
(you opened #1762 😉)

**Comment by lpugin** [comment]
> Anyway, it doesn't block merging, it just shows potential formatting problems.

Yes, that's right. Let's see how it works

**Pull request merged**
