### PR TITLE
Fix header include rule

### PR DESCRIPTION
**Pull request by alpha0010**
This was causing me build errors.

### CODE REVIEW

**Comment by lpugin** [comment]
The PR needs to be made to https://github.com/craigsapp/midifile. Once merged there we can update the MIDI library. For the record, it would be interesting to know under which building environment you have the error.

**Comment by alpha0010** [comment]
Thanks.

Xcode 12.5 with React Native framework targeting iOS.  It pulled in a header from RN (some sort of compatibility wrapper?) instead of the standard library.  That said, my Objective C skills/iOS native in general, are pretty much "copy paste programmer", so it could well be something on my end.

**Comment by craigsapp** [comment]
Fixed in Pull Request https://github.com/craigsapp/midifile/pull/91

**Comment by lpugin** [comment]
Integrated with 71f4f0e3a988627144dce676c58e11f654265c0a

**Comment by pablodelamerced** [comment]
Hi everyone,

I apologize for reopening this already closed issue, but as React Native is mentioned here, I wanted to ask a question: @alpha0010, do you use Verovio in React Native? If so, could you please provide guidance on how to use it?

Thanks a lot!

**Comment by alpha0010** [comment]
Basically what I did was follow [custom native module tutorial](https://reactnative.dev/docs/native-modules-intro), except for the implementation of functions, I forwarded calls to Verovio C++ code.  Bridged with JNI on Android, and a C wrapper on iOS.  The other piece to handle was bundling the font data folder; I did so with a zip archive that auto extracted on first use.

**Comment by miguelmunozfer** [comment]
> Basically what I did was follow [custom native module tutorial](https://reactnative.dev/docs/native-modules-intro), except for the implementation of functions, I forwarded calls to Verovio C++ code. Bridged with JNI on Android, and a C wrapper on iOS. The other piece to handle was bundling the font data folder; I did so with a zip archive that auto extracted on first use.

Hello! I am trying to integrate Verovio into a React Native project. I unzip the fonts in the Documents folder but it doesn't work. In which directory should I unzip the fonts?

**Pull request closed without merging**
