### PR TITLE
Steep slurs

### PR DESCRIPTION
**Pull request by DavidBauer1984**
The look of steep slurs is somewhat inconsistent due to the bound by `--slur-max-slope`.
This PR increases the default angle and does some improvements for the shape correction of steep slurs.
| Before | After |
| ------ | ----- |
| Before | After |

<details>
<summary>Show MEI example</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title />
            <respStmt />
         </titleStmt>
         <pubStmt><date isodate="2021-07-30" type="encoding-date">2021-07-30</date>
         </pubStmt>
      </fileDesc>
      <encodingDesc xml:id="encodingdesc-vaq0wr">
         <appInfo xml:id="appinfo-3qkozc">
            <application xml:id="application-x2dyp" isodate="2022-02-01T09:09:06" version="3.9.0-dev-4366ff2">
               <name xml:id="name-nod86h">Verovio</name>
               <p xml:id="p-m2aolf">Transcoded from MusicXML</p>
            </application>
         </appInfo>
      </encodingDesc>
   </meiHead>
   <music>
      <body>
         <mdiv xml:id="m9f26ke">
            <score xml:id="s1ude8r">
               <scoreDef xml:id="sh2smh1">
                  <staffGrp xml:id="sk5779y">
                     <staffGrp xml:id="S1-WudXPlSyWae1CbNa6dCgQA" bar.thru="true">
                        <staffDef xml:id="sf891ir" n="1" lines="5" ppq="8">
                           <clef xml:id="clef-1" shape="G" line="2" />
                           <keySig xml:id="key-1" sig="0" />
                           <meterSig xml:id="time-1" count="3" unit="8" />
                        </staffDef>
                        <staffDef xml:id="sj5lkyk" n="2" lines="5" ppq="8">
                           <clef xml:id="clef-2" shape="F" line="4" />
                           <keySig xml:id="key-2" sig="0" />
                           <meterSig xml:id="time-2" count="3" unit="8" />
                        </staffDef>
                        <grpSym xml:id="gvafifs" symbol="brace" />
                     </staffGrp>
                  </staffGrp>
               </scoreDef>
               <section xml:id="snjy8lw">
                  <measure xml:id="measure-0165-10280-10910-1-mdiv-1" n="49">
                     <staff xml:id="s31456p" n="1">
                        <layer xml:id="laebdlz" n="1">
                           <note xml:id="note-0165-10320-11030-2" dur.ppq="4" dur="8" oct="4" pname="b" stem.dir="down" />
                           <rest xml:id="rest-0165-10430-11070" dur.ppq="2" dur="16" />
                           <beam xml:id="bvn4fh2">
                              <note xml:id="note-0165-10470-11070-2" dur.ppq="2" dur="16" oct="4" pname="e" stem.dir="down" />
                              <note xml:id="note-0165-10520-11000-2" dur.ppq="2" dur="16" oct="5" pname="e" stem.dir="down" />
                           </beam>
                           <rest xml:id="rest-0165-10600-11070" dur.ppq="2" dur="16" />
                        </layer>
                     </staff>
                     <staff xml:id="scfxt6p" n="2">
                        <layer xml:id="lsar0ob" n="5">
                           <beam xml:id="brkd3z0">
                              <note xml:id="note-0165-10330-11280-2" dur.ppq="2" dur="16" oct="2" pname="e" stem.dir="down" />
                              <note xml:id="note-0165-10370-11210-2" dur.ppq="2" dur="16" oct="3" pname="e" stem.dir="down" />
                              <note xml:id="note-0165-10420-11150-2" dur.ppq="2" dur="16" oct="4" pname="e" stem.dir="down" />
                           </beam>
                           <rest xml:id="rest-0165-10480-11260" dur.ppq="2" dur="16" />
                           <rest xml:id="rest-0165-10530-11260" dur.ppq="2" dur="16" />
                           <clef xml:id="clef-11" shape="G" line="2" />
                           <note xml:id="note-0165-10590-11260-2" dur.ppq="2" dur="16" oct="4" pname="e" stem.dir="down" />
                        </layer>
                     </staff>
                     <slur xml:id="bow-0165-10490-11010" startid="#note-0165-10470-11070-2" endid="#note-0165-10520-11000-2" curvedir="above" />
                     <slur xml:id="bow-0165-10630-11200" startid="#note-0165-10590-11260-2" endid="#note-0165-10670-11190-2" curvedir="above" />
                  </measure>
                  <measure xml:id="measure-0165-10620-10910-1-mdiv-1" n="50">
                     <staff xml:id="sjn73nh" n="1">
                        <layer xml:id="l2jhld3" n="1">
                           <rest xml:id="rest-0165-10680-11070" dur.ppq="2" dur="16" />
                           <beam xml:id="bxfk0vy">
                              <note xml:id="note-0165-10710-11000-2" dur.ppq="2" dur="16" oct="5" pname="e" stem.dir="down" />
                              <note xml:id="note-0165-10760-10940-2" dur.ppq="2" dur="16" oct="6" pname="e" stem.dir="down" />
                           </beam>
                           <rest xml:id="rest-0165-10830-11070" dur.ppq="2" dur="16" />
                           <rest xml:id="rest-0165-10880-11070" dur.ppq="2" dur="16" />
                        </layer>
                     </staff>
                     <staff xml:id="sb8v57f" n="2">
                        <layer xml:id="lok38oo" n="5">
                           <note xml:id="note-0165-10670-11190-2" dur.ppq="2" dur="16" oct="5" pname="e" stem.dir="down" />
                           <rest xml:id="rest-0165-10730-11260" dur.ppq="2" dur="16" />
                           <rest xml:id="rest-0165-10770-11260" dur.ppq="2" dur="16" />
                           <beam xml:id="babg3k7">
                              <note xml:id="note-0165-10820-11200-2" dur.ppq="2" dur="16" oct="5" pname="d" stem.dir="down" accid="s" />
                              <note xml:id="note-0165-10860-11190-2" dur.ppq="2" dur="16" oct="5" pname="e" stem.dir="down" />
                           </beam>
                           <rest xml:id="rest-0165-10930-11260" dur.ppq="2" dur="16" />
                        </layer>
                     </staff>
                     <slur xml:id="bow-0165-10740-10950" startid="#note-0165-10710-11000-2" endid="#note-0165-10760-10940-2" curvedir="above" />
                     <slur xml:id="bow-0165-10840-11180" startid="#note-0165-10820-11200-2" endid="#note-0165-10860-11190-2" curvedir="above" />
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```
</details>

### CODE REVIEW

**Comment by craigsapp** [comment]
Readability of the slur would be improved with slightly more curvature on this slur (in particular due to the slur nearly touching the ledger line, but even without the ledger lines it feels too straight):

Screen Shot 2022-03-24 at 8 00 18 AM


An enhancement to think about in the future is notehead justification of the slur ends in such cases.  This is somewhat related to issue https://github.com/rism-digital/verovio/issues/2729.

In the following example rendering, the steep slur is left justified to both noteheads to avoid the slur end to seem too close to the ending notehead:

Screen Shot 2022-03-24 at 7 47 13 AM

https://s9.imslp.org/files/imglnks/usimg/5/50/IMSLP421523-PMLP14377-Beethoven.WoO59.Fur.Elise.pdf


Here is one that starts left-justified and then goes (almost) centered (widening the slur to reduce the angle).  I like this one the best:
Screen Shot 2022-03-24 at 7 51 38 AM

https://s9.imslp.org/files/imglnks/usimg/4/44/IMSLP600067-PMLP14377-Beethoven_Fur_Elise.pdf

Here is one that starts centered and ends left-justified:

Screen Shot 2022-03-24 at 7 55 00 AM

https://s9.imslp.org/files/imglnks/usimg/0/01/IMSLP616176-PMLP14377-Fuer_E.pdf

And one that is exactly centered on both ends.  But the slur curvature is larger than your rendering in the initial example.  The vertical positioning of the slur end looks better than in the initial example (which should also be fixed by a larger curvature):

Screen Shot 2022-03-24 at 7 56 33 AM

https://s9.imslp.org/files/imglnks/usimg/d/d9/IMSLP05929-Ludwig_van_Beethoven_-_Fuer_Elise.pdf






Source page: https://imslp.org/wiki/F%C3%BCr_Elise%2C_WoO_59_(Beethoven%2C_Ludwig_van)

**Comment by DavidBauer1984** [comment]
@craigsapp I've added some more curvature, the look is now similar to the last example in your list. Anyway one has to be careful that improvements for the example at hand do not mess up other cases at the same time.
SteepSlurs

**Comment by lpugin** [comment]
Looks good to me!

image

**Comment by craigsapp** [comment]
> Anyway one has to be careful that improvements for the example at hand do not mess up other cases at the same time.

Better you than me 😉 

I will point out that the MuseData printing system's handling of slurs is better than with verovio, since they are usually less distracting.   Here is a full work sample:  https://pdf.musedata.org/?id=beet-quartet-no16

It has basic slur layout down very well, although it will have problems with more extreme slurs.

Here are the _Für Elise_ measures typeset from MuseData (using the _muse2ps_ command-line version of the printing system), with no manual interventions:

Screen Shot 2022-03-25 at 5 22 56 AM

<details>
<summary>
Click to view MuseData for above example
</summary>

```



03/25/2022 hum2muse
WK#:1 MV#:1
Header Record 6: source
Header Record 7: work title
Header Record 8: movement title

Header Record 10
Group memberships: score
score: part 1 of 2
$  Q:4   T:3/8   C:4
P C0:x0
B4     2      1 e     d
rest   1      1 s
E4     1      1 s     d  [[     (
E5     1      1 s     d  ]]     )
rest   1      1 s
measure 50
rest   1      1 s
E5     1      1 s     d  [[     (
E6     1      1 s     d  ]]     )
rest   1      1 s
rest   1      1 s
irest  1      1 s
measure
/END
/eof



03/25/2022 hum2muse
WK#:1 MV#:1
Header Record 6: source
Header Record 7: work title
Header Record 8: movement title

Header Record 10
Group memberships: score
score: part 2 of 2
$  Q:4   T:3/8   C:22
P C0:x0
E2     1      1 s     d  [[
E3     1      1 s     d  ==
E4     1      1 s     d  ]]
rest   1      1 s
rest   1      1 s
$      C:4
E4     1      1 s     d         (
measure 50
E5     1      1 s     d         )
rest   1      1 s
rest   1      1 s
D#5    1      1 s     d  [[     (
E5     1      1 s     d  ]]     )
rest   1      1 s
measure
/END
/eof
//
```

</details>

I am also noticing an illegal vertical placement of the beam end in the verovio rendering of this beamed group:

Screen Shot 2022-03-25 at 6 08 35 AM


------------------------------

Here is a study of how it deals with steep slurs:
Screen Shot 2022-03-25 at 5 44 12 AM


<details>
<summary>
Click to view MuseData for above example
</summary>

```xml



03/25/2022 hum2muse
WK#:1 MV#:1
Header Record 6: source
Header Record 7: work title
Header Record 8: movement title

Header Record 10
Group memberships: score
score: part 1 of 1
$  Q:4   T:4/4   C:4
P C0:x0
B4     1      1 s     d  [[     (
C5     1      1 s     d  ]]     )
B4     1      1 s     d  [[     (
D5     1      1 s     d  ]]     )
B4     1      1 s     d  [[     (
E5     1      1 s     d  ]]     )
B4     1      1 s     d  [[     (
F5     1      1 s     d  ]]     )
B4     1      1 s     d  [[     (
G5     1      1 s     d  ]]     )
B4     1      1 s     d  [[     (
A5     1      1 s     d  ]]     )
B4     1      1 s     d  [[     (
B5     1      1 s     d  ]]     )
B4     1      1 s     d  [[     (
C6     1      1 s     d  ]]     )
measure 2
B4     1      1 s     d  [[     (
D6     1      1 s     d  ]]     )
B4     1      1 s     d  [[     (
E6     1      1 s     d  ]]     )
B4     1      1 s     d  [[     (
F6     1      1 s     d  ]]     )
B4     1      1 s     d  [[     (
G6     1      1 s     d  ]]     )
B4     1      1 s     d  [[     (
A6     1      1 s     d  ]]     )
B4     1      1 s     d  [[     (
B6     1      1 s     d  ]]     )
B4     1      1 s     d  [[     (
C7     1      1 s     d  ]]     )
B4     1      1 s     d  [[     (
D7     1      1 s     d  ]]     )
measure
/END
/eof
//
```

</details>

<details>
<summary>
Click to view MEI data for above example
</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2022-03-25T05:47:52" version="3.8.0-dev-c01277e">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mu8bh4q">
    <score xml:id="s78qk69">
     <scoreDef xml:id="s62kb8i">
      <staffGrp xml:id="sqks0o8">
       <staffDef xml:id="sum0tzs" n="1" lines="5">
        <clef xml:id="cydwnv2" shape="G" line="2" />
        <meterSig xml:id="metersig-L2F1" count="4" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="spibhi9" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <beam xml:id="beam-L4F1-L5F1">
          <note xml:id="note-L4F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L5F1" type="placed" dur="16" oct="5" pname="c" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L6F1-L7F1">
          <note xml:id="note-L6F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L7F1" type="placed" dur="16" oct="5" pname="d" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L8F1-L9F1">
          <note xml:id="note-L8F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L9F1" type="placed" dur="16" oct="5" pname="e" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L10F1-L11F1">
          <note xml:id="note-L10F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L11F1" type="placed" dur="16" oct="5" pname="f" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L12F1-L13F1">
          <note xml:id="note-L12F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L13F1" type="placed" dur="16" oct="5" pname="g" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L14F1-L15F1">
          <note xml:id="note-L14F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L15F1" type="placed" dur="16" oct="5" pname="a" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L16F1-L17F1">
          <note xml:id="note-L16F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L17F1" type="placed" dur="16" oct="5" pname="b" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L18F1-L19F1">
          <note xml:id="note-L18F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L19F1" type="placed" dur="16" oct="6" pname="c" stem.dir="down" accid.ges="n" />
         </beam>
        </layer>
       </staff>
       <slur xml:id="slur-L4F1-L5F1" staff="1" startid="#note-L4F1" endid="#note-L5F1" />
       <slur xml:id="slur-L6F1-L7F1" staff="1" startid="#note-L6F1" endid="#note-L7F1" />
       <slur xml:id="slur-L8F1-L9F1" staff="1" startid="#note-L8F1" endid="#note-L9F1" />
       <slur xml:id="slur-L10F1-L11F1" staff="1" startid="#note-L10F1" endid="#note-L11F1" />
       <slur xml:id="slur-L12F1-L13F1" staff="1" startid="#note-L12F1" endid="#note-L13F1" />
       <slur xml:id="slur-L14F1-L15F1" staff="1" startid="#note-L14F1" endid="#note-L15F1" />
       <slur xml:id="slur-L16F1-L17F1" staff="1" startid="#note-L16F1" endid="#note-L17F1" />
       <slur xml:id="slur-L18F1-L19F1" staff="1" startid="#note-L18F1" endid="#note-L19F1" />
      </measure>
      <measure xml:id="measure-L20" n="2">
       <staff xml:id="staff-L20F1N1" n="1">
        <layer xml:id="layer-L20F1N1" n="1">
         <beam xml:id="beam-L21F1-L22F1">
          <note xml:id="note-L21F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L22F1" type="placed" dur="16" oct="6" pname="d" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L23F1-L24F1">
          <note xml:id="note-L23F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L24F1" type="placed" dur="16" oct="6" pname="e" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L25F1-L26F1">
          <note xml:id="note-L25F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L26F1" type="placed" dur="16" oct="6" pname="f" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L27F1-L28F1">
          <note xml:id="note-L27F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L28F1" type="placed" dur="16" oct="6" pname="g" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L29F1-L30F1">
          <note xml:id="note-L29F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L30F1" type="placed" dur="16" oct="6" pname="a" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L31F1-L32F1">
          <note xml:id="note-L31F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L32F1" type="placed" dur="16" oct="6" pname="b" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L33F1-L34F1">
          <note xml:id="note-L33F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L34F1" type="placed" dur="16" oct="7" pname="c" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L35F1-L36F1">
          <note xml:id="note-L35F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L36F1" type="placed" dur="16" oct="7" pname="d" stem.dir="down" accid.ges="n" />
         </beam>
        </layer>
       </staff>
       <slur xml:id="slur-L21F1-L22F1" staff="1" startid="#note-L21F1" endid="#note-L22F1" />
       <slur xml:id="slur-L23F1-L24F1" staff="1" startid="#note-L23F1" endid="#note-L24F1" />
       <slur xml:id="slur-L25F1-L26F1" staff="1" startid="#note-L25F1" endid="#note-L26F1" />
       <slur xml:id="slur-L27F1-L28F1" staff="1" startid="#note-L27F1" endid="#note-L28F1" />
       <slur xml:id="slur-L29F1-L30F1" staff="1" startid="#note-L29F1" endid="#note-L30F1" />
       <slur xml:id="slur-L31F1-L32F1" staff="1" startid="#note-L31F1" endid="#note-L32F1" />
       <slur xml:id="slur-L33F1-L34F1" staff="1" startid="#note-L33F1" endid="#note-L34F1" />
       <slur xml:id="slur-L35F1-L36F1" staff="1" startid="#note-L35F1" endid="#note-L36F1" />
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>


In these cases it looks like the slur is about 50% left-justified to the noteheads on each end of the slur starting with the interval of a fifth.   This adjustment is triggered by the slur steepness rather than the interval, since a wider music spacing delays the adjustment to larger intervals:

Screen Shot 2022-03-25 at 5 56 25 AM

Now it is starting around the beginning of the second line of music (octave + fifth).

**Comment by DavidBauer1984** [comment]
@craigsapp Thanks I will take that as inspiration. One thing that I notice is that in MuseData shorter slurs are drawn with less thickness. Compared to this our slurs appear quite fat.

Here is the comparison for the example above:
Slurs

We should improve things step by step.

**Pull request merged**
