### PR TITLE
Added support for chords and measures in getTimeForElement()

### PR DESCRIPTION
**Pull request by gitelicious**
Fixing #2237

### CODE REVIEW

**Comment by lpugin** [comment]
Looks good. Could you please fill and sign the CLA? https://book.verovio.org/introduction/licensing.html Thanks!

**Comment by gitelicious** [comment]
No, sorry. I am not willing to sign any documents when contributing to open source projects for free. Just use the code in any way you see fit. Attribution is not needed.

**Comment by lpugin** [comment]
No problem, that's fine. People can use your code from your repo.

**Comment by gitelicious** [comment]
Wow, that was a rather... surprising way of dealing with pull requests. Never seen such a hostile contribution procedure in an open source project before.

**Comment by ahankinson** [comment]
I don't think there was any hostility intended. CLAs are a standard practice for contributions as they provide legal certainty for all people involved.

https://owncloud.com/news/contributor-license-agreements-important-legal-certainty/

**Comment by lpugin** [comment]
Nothing hostile at all. It is only a standard licensing procedure, and it has nothing to do with the fact that you contribute for free or not. It is totally up to you to decide if you want to sign it or not, and we fully respect your choice.

**Comment by gitelicious** [comment]
I see, file is attached. Nevertheless, the hurdle for new contributors seems to be quite high.[verovio-cla_signed.pdf](https://github.com/rism-digital/verovio/files/6790501/verovio-cla_signed.pdf)

**Comment by lpugin** [comment]
Great, thanks.

**Comment by craigsapp** [comment]
Somewhat related: https://www.computerworld.com/article/2545099/update--microsoft-wants-royalties-for-open-source-software.html

**Comment by samuelbradshaw** [comment]
@gitelicious, thank you for implementing this! Have you looked into how difficult it would be to add support for chords and measures in getElementsAtTime() as well, or did you only look at getTimeForElement()?

**Pull request merged**
