### PR TITLE
Unify spelling and shrink size of SVG

### PR DESCRIPTION
**Pull request by rettinghaus**
This PR unifies the spelling of color in the code and makes the SVG a bit smaller by dropping trailing zeros.

### CODE REVIEW

**Comment by ahankinson** [comment]
I think `%g` can emit scientific notation as a format… is this valid input in the places where you’ve switched it?

https://stackoverflow.com/questions/827499/string-format-with-g-in-c

**Comment by craigsapp** [comment]
`%g` might be interesting for this issue (which I was too lazy to implement). 

https://github.com/rism-digital/verovio/issues/975

 Scientific notation avoidance would be important as @ahankinson mentions.

**Comment by rettinghaus** [comment]
It's valid. Most of these values are be between 0 and 1. If something weird should happen with scaling we're safe anyway, because [SVG supports scientific notation](https://www.w3.org/TR/SVG11/types.html#DataTypeNumber).  

[arpeggios_in_chords.svg.zip](https://github.com/rism-digital/verovio/files/11515860/arpeggios_in_chords.svg.zip)

**Comment by rettinghaus** [comment]
Ok, I reverted the cases where there could be a potential risk. Still, where we only have values of 0 or 1, I don't see the point in writing `0.000000` and `1.000000`.

**Comment by lpugin** [comment]
>  don't see the point in writing `0.000000` and `1.000000`.

I don't think it is great. But since most of the users do not look at the SVG code, I don't think it is a big deal. Machines do not care.

**Comment by rettinghaus** [comment]
You don't like it, I don't like it, @craigsapp doesn't like it. And, as you said, machines do not care. ;-)

**Comment by lpugin** [comment]
Since we agree that machines do not care, could you revert the other ones? Thanks!

**Pull request merged**
