### PR TITLE
Integrate lates changes from DDMAL

### PR DESCRIPTION
**Pull request by lpugin**

### CODE REVIEW

**Comment by lpugin** [comment]
@yinanazhou could you try to rebase the DDMAL branch?

**Comment by yinanazhou** [comment]
> @yinanazhou could you try to rebase the DDMAL branch?

Hi, I've merged the changes to [this branch](https://github.com/DDMAL/verovio/tree/update-verovio), but I'm getting a negative width/height value error in the console. Could you please guide me on where I should look into? Thanks!

**Comment by lpugin** [comment]
Sure. Please post the file that is causing the issue, and all not non-default parameters you are setting to call the toolkit.

**Comment by yinanazhou** [comment]
Hi, I haven't identified the specific file causing the issue yet. Below is a snippet of the SVG output, where the x`/`y`/`width`/`height` value can be negative and the number is quite large. I wonder if it is related to any changes regarding `drawing` and `logical` system? I've checked `src/view_element.cpp` and `src/svgdevicecontext.cpp` but haven't find anything.

image

This is the command line I used to build verovio for neon:
`./buildToolkit -x "Gootville,Petaluma" -DHPX`

And these are the options neon uses:
```
this.toolkit.setOptions({
      from: 'mei',
      footer: 'none',
      header: 'none',
      pageMarginLeft: 0,
      pageMarginTop: 0,
      font: 'Bravura',
      useFacsimile: true,
    });
```

Any insights would be appreciated. Merry Christmas :)

**Comment by lpugin** [comment]
Please send the input file you are using

**Comment by yinanazhou** [comment]
Sorry, forgot the most important file...
[005r.xml.zip](https://github.com/rism-digital/verovio/files/13772836/005r.xml.zip)

**Comment by lpugin** [comment]
The problem is that there `facs@lry` and `facs@lrx` were not read. I don't know how this used to work in your branch because this causes the staff size to have an unrealistic value here:
https://github.com/rism-digital/verovio/blob/d89dc949357cb22a8fd062515af56bf3b533cb70/src/staff.cpp#L177-L181

I fixed it here https://github.com/rism-digital/verovio/commit/d89dc949357cb22a8fd062515af56bf3b533cb70.

Rendering your test file works on this branch:
image

I am going to suggest some additional changes in the facsimile handling since we are going to use it in other contexts. I will open an issue on the [ddmal/verovio] (https://github.com/ddmal/verovio) repository. Once resolve, please do make sure to always make a PR to the [rism-digital/verovio](https://github.com/rism-digital/verovio) everytime you merge something in your develop branch. Pinging @fujinaga

**Pull request merged**
