### PR TITLE
Humdrum: Fix typo that prevented mxhm data from being properly read

### PR DESCRIPTION
**Pull request by gregchapman-dev**
Get basic above/below working for mxhm as well (and stop defaulting to below, instead default to unspecified).

### CODE REVIEW

**Comment by gregchapman-dev** [comment]
If you want to default to above or below for cdata, deg, etc, I can do that.  adata and bdata explicitly default to above and below now, of course.

**Comment by craigsapp** [comment]
For `**cdata` the default position should be below (but can be changed explicitly with `*below`/`*above`).   `**deg` should be below by default, but `**mxhm` default position should be above (since that is where chord symbols are usually placed).

Text for `**cdata`, `**adata`, and `**bdata`:


```tsv
**kern	**cdata	**adata	**bdata
1cc	C	.	.
*	*above	*	*
1cc	Ca	.	.
*	*below	*	*
1cc	Cb	.	.
1a	.	A	.
*	*	*below	*
1a	.	Ab	.
*	*	*above	*
1c	.	Aa	.
1b	.	.	B
*	*	*	*above
1b	.	.	Ba
*	*	*	*below
1b	.	.	Bb
=	=	=	=
*-	*-	*-	*-
```

[Veiw in VHV](https://verovio.humdrum.org?t=KiprZXJuCSoqY2RhdGEJKiphZGF0YQkqKmJkYXRhCjFjYwlDCS4JLgoqCSphYm92ZQkqCSoKMWNjCUNhCS4JLgoqCSpiZWxvdwkqCSoKMWNjCUNiCS4JLgoxYQkuCUEJLgoqCSoJKmJlbG93CSoKMWEJLglBYgkuCioJKgkqYWJvdmUJKgoxYwkuCUFhCS4KMWIJLgkuCUIKKgkqCSoJKmFib3ZlCjFiCS4JLglCYQoqCSoJKgkqYmVsb3cKMWIJLgkuCUJiCj0JPQk9CT0KKi0JKi0JKi0JKi0K)

Screenshot 2024-04-02 at 11 10 43 PM

(the data are not all aligned horizontally because they are in different spines).

**Comment by craigsapp** [comment]
`**harm` default position should be below as well:

```tsv
**harm	**kern
*C:	*
I	1c
IV	1f
V	1g
vib	1cc
V7	1g
I	1c
=	=
*-	*-
```

[View in VHV](https://verovio.humdrum.org?t=KipoYXJtCSoqa2VybgoqQzoJKgpJCTFjCklWCTFmClYJMWcKdmliCTFjYwpWNwkxZwpJCTFjCj0JPQoqLQkqLQo=)

Screenshot 2024-04-02 at 11 25 52 PM

So all harmonic sorts of data should default to below as far as I can think of, except for `**mxhm`.

-------------------------

Note that `**harm` spines should typically go before any `**kern` spines, which generally means the data applies to all spines (parts). I.e., it is a system-level spine rather than a staff-level spine.   Forcing `**harm` above the system:

```tsv
**harm	**kern	**kern
*above	*	*
*C:	*	*
I	1c	1e
IV	1f	1a
V	1g	1b
vib	1cc	1e
V7	1g	1b
I	1c	1e
=	=	=
*-	*-	*-
```

[View in VHV](https://verovio.humdrum.org?t=KipoYXJtCSoqa2VybgkqKmtlcm4KKmFib3ZlCSoJKgoqQzoJKgkqCkkJMWMJMWUKSVYJMWYJMWEKVgkxZwkxYgp2aWIJMWNjCTFlClY3CTFnCTFiCkkJMWMJMWUKPQk9CT0KKi0JKi0JKi0K)

Currently not correct (you could fix if you want 😉 ):

Screenshot 2024-04-02 at 11 35 03 PM

(should be above `@staff="1"` rather than `@staff="[bottom-staff-number]"`)

**Comment by lpugin** [comment]
@craigsapp I'll let you merge it

**Pull request merged**
