### PR TITLE
Handle lyric verse number when converting from MusicXML

### PR DESCRIPTION
**Pull request by samuelbradshaw**
This pull request improves MusicXML import by converting MusicXML verse numbers into MEI labels (see issue #2235).

The `<text>` element in a `<lyric>` will be converted into `<label>` if:
1. The text content is not empty.
2. The text content contains nothing other than digits and/or periods.
3. The next sibling is an elision.

Example input (MusicXML):
```
	<lyric default-y="-120" number="2">
		<syllabic>single</syllabic>
		<text>2.</text>
		<elision> </elision>
		<syllabic>single</syllabic>
		<text>“Come,</text>
	</lyric>
```

Output (MEI):
```
	<verse xml:id="verse-0000002112875384" n="2">
		<label xml:id="label-0000000306992096">2.</label>
		<syl xml:id="syl-0000000612622437" con="s" wordpos="s">“Come,</syl>
	</verse>
```

### CODE REVIEW

**Comment by samuelbradshaw** [comment]
Per suggestions in #2235, this has been updated to use RegEx and to support additional verse number formats.

**Comment by lpugin** [comment]
Have you run clang-format? See https://book.verovio.org/contributing/guidelines.html#formatting

**Comment by samuelbradshaw** [comment]
Done.

**Comment by lpugin** [comment]
Many thanks for the contribution! Please do not forget to fill the CLA https://rism.digital/resources/verovio-cla.pdf. Thanks!

**Pull request merged**
