### PR TITLE
Code style updates

### PR DESCRIPTION
**Pull request by rettinghaus**
* prefer C++11 `using` keyword for alias declaration
* use C++11 braced-init-list
* replace deprecated headers

### CODE REVIEW

**Comment by lpugin** [comment]
Thanks. Beyond the preference, why would you change `typedef` to `using`? What difference does it make? As far as I know, `using` is useful when doing templates, but we do not do that.

**Comment by rettinghaus** [comment]
It's really just about readability.

**Comment by ahankinson** [comment]
I can't actually see anything in PEP 257 that would necessitate those changes? Would you mind pointing out the line or sentence?

**Comment by rettinghaus** [comment]
> The docstring is a phrase ending in a period. It prescribes the function or method’s effect as a command (“Do this”, “Return that”), not as a description; e.g. don’t write “Returns the pathname …”.

https://peps.python.org/pep-0257/#one-line-docstrings

**Comment by rettinghaus** [comment]
rebased, staying with `typedef` for the time being.

**Pull request merged**
