### PR TITLE
Fix for the beams with first element rest

### LINKED ISSUE #2175: Sixteenth rests in beams badly rendered if in first position
Hello,

It seems that when sixteenth rests in beams appear in first position, the beam is badly rendered.
On this example, with the same notes, it's fine when placed on the 4th, 3rd, or 2nd position, but when it's in first position, the beam is broken:

Capture d’écran 2021-05-05 à 22 21 56

And here's the code that produces this result:

~~~ xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo />
        </encodingDesc>
        <workList>
            <work>
                <title />
            </work>
        </workList>
    </meiHead>
 <music>
  <body>
   <mdiv>
    <score>
       <scoreDef xml:id="scoredef-0000000578035858">
         <staffGrp xml:id="staffgrp-0000001760475413">
               <staffDef xml:id="staffdef-0000001967435478" n="1" lines="5" ppq="8">
                  <clef xml:id="clef-0000000788455254" shape="G" line="2" />
                  <keySig xml:id="keysig-0000001618717358" mode="major" sig="3s" />
                  <meterSig xml:id="msig-0000001360290431" count="4" unit="4" />
               </staffDef>
         </staffGrp>
      </scoreDef>
      <section xml:id="section-0000001953199539">
         <measure xml:id="measure-0000000138773945" n="0">
            <staff xml:id="staff-0000001556924724" n="1">
               <layer xml:id="layer-0000000290978060" n="1">
                   <beam xml:id="m-315">
                       <note xml:id="m-314" artic="stacc" dur="16" dur.ges="64p" layer="1" oct="6" pname="d" pnum="86" staff="1" stem.dir="down"/>
                       <note xml:id="m-316" artic="stacc acc" dur="16" dur.ges="64p" layer="1" oct="6" pname="e" pnum="87" staff="1" stem.dir="down">
                           <accid xml:id="m-317" accid="f"/>
                       </note>
                       <note xml:id="m-318" artic="stacc" dur="16" dur.ges="64p" layer="1" oct="5" pname="f" pnum="78" staff="1" stem.dir="down">
                           <accid xml:id="m-319" accid="s"/>
                       </note>
                       <rest xml:id="m-320" dur="16" dur.ges="64p"/>
                   </beam>
                   <beam xml:id="m-308">
                       <note xml:id="m-306" artic="stacc" dur="16" dur.ges="64p" layer="1" oct="6" pname="d" pnum="86" staff="1" stem.dir="down"/>
                       <note xml:id="m-307" artic="stacc acc" dur="16" dur.ges="64p" layer="1" oct="6" pname="e" pnum="87" staff="1" stem.dir="down">
                           <accid xml:id="m-309" accid="f"/>
                       </note>
                       <rest xml:id="m-310" dur="16" dur.ges="64p"/>
                       <note xml:id="m-312" artic="stacc" dur="16" dur.ges="64p" layer="1" oct="5" pname="f" pnum="78" staff="1" stem.dir="down">
                           <accid xml:id="m-313" accid="s"/>
                       </note>
                   </beam>
                   <beam xml:id="m-300">
                       <note xml:id="m-299" artic="stacc" dur="16" dur.ges="64p" layer="1" oct="6" pname="d" pnum="86" staff="1" stem.dir="down"/>
                       <rest xml:id="m-301" dur="16" dur.ges="64p"/>
                       <note xml:id="m-302" artic="stacc acc" dur="16" dur.ges="64p" layer="1" oct="6" pname="e" pnum="87" staff="1" stem.dir="down">
                           <accid xml:id="m-303" accid="f"/>
                       </note>
                       <note xml:id="m-304" artic="stacc" dur="16" dur.ges="64p" layer="1" oct="5" pname="f" pnum="78" staff="1" stem.dir="down">
                           <accid xml:id="m-305" accid="s"/>
                       </note>
                   </beam>
                   <beam xml:id="m-291">
                       <rest xml:id="m-292" dur="16" dur.ges="64p"/>
                       <note xml:id="m-294" artic="stacc" dur="16" dur.ges="64p" layer="1" oct="6" pname="d" pnum="86" staff="1" stem.dir="down"/>
                       <note xml:id="m-295" artic="stacc acc" dur="16" dur.ges="64p" layer="1" oct="6" pname="e" pnum="87" staff="1" stem.dir="down">
                           <accid xml:id="m-296" accid="f"/>
                       </note>
                       <note xml:id="m-297" artic="stacc" dur="16" dur.ges="64p" layer="1" oct="5" pname="f" pnum="78" staff="1" stem.dir="down">
                           <accid xml:id="m-298" accid="s"/>
                       </note>
                   </beam>
               </layer>
            </staff>
         </measure>
      </section>
   </score>
   </mdiv>
  </body>
 </music>
</mei>
~~~

Thanks

### PR DESCRIPTION
**Pull request by Monceber**
- changed code to use firstNoteOrChord instead of the first reference, which could be a rest (closes #2175)

### CODE REVIEW

**Comment by lpugin** [comment]
It looks like it crashed on https://github.com/rism-digital/verovio.org/blob/gh-pages/_tests/rest/rest-010.mei

**Comment by Monceber** [comment]
Yeah, seems so. Have no idea why, I get no crashes at all running that file:
image

**Comment by rettinghaus** [comment]
I could reproduce this in the Python binding, but I have no clue what's happening here.

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   _verovio_module_3_9_1.so      	0x0000000109a0e900 vrv::BeamSegment::CalcBeamPosition(vrv::Doc*, vrv::Staff*, vrv::Layer*, vrv::BeamDrawingInterface*, bool) + 736
1   _verovio_module_3_9_1.so      	0x0000000109a0d9eb vrv::BeamSegment::CalcBeam(vrv::Layer*, vrv::Staff*, vrv::Doc*, vrv::BeamDrawingInterface*, vrv::data_BEAMPLACE, bool) + 267
2   _verovio_module_3_9_1.so      	0x0000000109a110d5 vrv::Beam::CalcStem(vrv::FunctorParams*) + 165
3   _verovio_module_3_9_1.so      	0x0000000109b26a05 vrv::Functor::Call(vrv::Object*, vrv::FunctorParams*) + 37
4   _verovio_module_3_9_1.so      	0x0000000109b25452 vrv::Object::Process(vrv::Functor*, vrv::FunctorParams*, vrv::Functor*, std::__1::vector<vrv::Comparison*, std::__1::allocator<vrv::Comparison*> >*, int, bool, bool) + 210
5   _verovio_module_3_9_1.so      	0x0000000109b254f2 vrv::Object::Process(vrv::Functor*, vrv::FunctorParams*, vrv::Functor*, std::__1::vector<vrv::Comparison*, std::__1::allocator<vrv::Comparison*> >*, int, bool, bool) + 370
6   _verovio_module_3_9_1.so      	0x0000000109b254f2 vrv::Object::Process(vrv::Functor*, vrv::FunctorParams*, vrv::Functor*, std::__1::vector<vrv::Comparison*, std::__1::allocator<vrv::Comparison*> >*, int, bool, bool) + 370
7   _verovio_module_3_9_1.so      	0x0000000109b254f2 vrv::Object::Process(vrv::Functor*, vrv::FunctorParams*, vrv::Functor*, std::__1::vector<vrv::Comparison*, std::__1::allocator<vrv::Comparison*> >*, int, bool, bool) + 370
8   _verovio_module_3_9_1.so      	0x0000000109b254f2 vrv::Object::Process(vrv::Functor*, vrv::FunctorParams*, vrv::Functor*, std::__1::vector<vrv::Comparison*, std::__1::allocator<vrv::Comparison*> >*, int, bool, bool) + 370
9   _verovio_module_3_9_1.so      	0x0000000109b254f2 vrv::Object::Process(vrv::Functor*, vrv::FunctorParams*, vrv::Functor*, std::__1::vector<vrv::Comparison*, std::__1::allocator<vrv::Comparison*> >*, int, bool, bool) + 370
10  _verovio_module_3_9_1.so      	0x0000000109b61872 vrv::Page::LayOutHorizontally() + 1394
11  _verovio_module_3_9_1.so      	0x0000000109a2fe4e vrv::Doc::CastOffDocBase(bool, bool, bool) + 142
12  _verovio_module_3_9_1.so      	0x0000000109bb8f38 vrv::Toolkit::LoadData(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 760
13  _verovio_module_3_9_1.so      	0x0000000109bb7f46 vrv::Toolkit::LoadFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 486
14  _verovio_module_3_9_1.so      	0x00000001099f183b _wrap_toolkit_loadFile(_object*, _object*) + 155

```

**Comment by lpugin** [comment]
Got it fixed here #2179

**Pull request closed without merging**
