### PR TITLE
Improve beam angle

### LINKED ISSUE #1853: Inconsistent beam angle
In the following example, the beam angle for each beam group should be approximately equal; however, the third example has a horizontal beam for no apparent reason.

Screen Shot 2020-11-27 at 7 24 46 AM

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2020-11-27T07:25:03" version="3.1.0-dev-c299a50">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000000596655207">
    <score xml:id="score-0000001444024715">
     <scoreDef xml:id="scoredef-0000001014915397">
      <staffGrp xml:id="staffgrp-0000001492347912">
       <staffDef xml:id="staffdef-0000001781765410" n="1" lines="5">
        <clef xml:id="clef-0000000190463810" shape="G" line="2" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-0000000905848310" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <beam xml:id="beam-L3F1-L4F1">
          <note xml:id="note-L3F1" dur="8" oct="4" pname="c" accid.ges="n" />
          <note xml:id="note-L4F1" dur="8" oct="4" pname="d" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L5F1-L7F1">
          <note xml:id="note-L5F1" dur="8" oct="4" pname="c" accid.ges="n" />
          <note xml:id="note-L6F1" dur="8" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L7F1" dur="8" oct="4" pname="e" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L8F1-L11F1">
          <note xml:id="note-L8F1" type="marked" dur="8" oct="4" pname="c" color="red" accid.ges="n" />
          <note xml:id="note-L9F1" type="marked" dur="8" oct="4" pname="d" color="red" accid.ges="n" />
          <note xml:id="note-L10F1" type="marked" dur="8" oct="4" pname="e" color="red" accid.ges="n" />
          <note xml:id="note-L11F1" type="marked" dur="8" oct="4" pname="f" color="red" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L12F1-L16F1">
          <note xml:id="note-L12F1" dur="8" oct="4" pname="c" accid.ges="n" />
          <note xml:id="note-L13F1" dur="8" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L14F1" dur="8" oct="4" pname="e" accid.ges="n" />
          <note xml:id="note-L15F1" dur="8" oct="4" pname="f" accid.ges="n" />
          <note xml:id="note-L16F1" dur="8" oct="4" pname="g" accid.ges="n" />
         </beam>
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

### PR DESCRIPTION
**Pull request by Monceber**
closes #1853 

Added some more consistency to the beam angle:
image

### CODE REVIEW

**Comment by lpugin** [comment]
Thanks! Many beams in the test suite are now much steeper. Not that this is necessary bad, but I will take the time to look at it. In the meantime, could you look at example `rest-010` ? The stem of the middle note in the first beam is now a bit short, isn't it?

image

**Comment by Monceber** [comment]
Should be better now:
image

**Comment by lpugin** [comment]
@Monceber do you know why the second beam of first staff is now straight in this example? Because it is 32nd notes? It looks awkward to me.

image

There are some more examples in beam. See this

image

Could you double check? Thanks!

**Comment by lpugin** [comment]
Example added to the test-suite https://github.com/rism-digital/verovio.org/commit/3d3332739268545798714f8642532846aa185984

**Pull request merged**
