### PR TITLE
ci: include macos-14 in python wheel workflow

### PR DESCRIPTION
**Pull request by musicEnfanthen**
This PR updates the python wheel workflow to include builds from the new macos-14-runner and arm64. arm64 builds are excluded for any other os than macos-14.

Tested in https://github.com/musicEnfanthen/verovio-pypi-test/actions/runs/8984209437

### CODE REVIEW

**Comment by ahankinson** [comment]
You're a star! ⭐ 

Could you rebase this against the `develop` branch? There's a lot of cruft I want to get rid of on this one, but `develop` (and `master`) should be up-to-date.

**Comment by musicEnfanthen** [comment]
@ahankinson I thought it might be worth to have a test run on develop-pypi first?

**Comment by ahankinson** [comment]
We can merge develop into develop-pypi and give it a test. That's the "normal" method, and if you've tested it then there's not much reason it won't work.

**Comment by ahankinson** [comment]
It should always go `develop` --> `develop-pypi`. Going the other way isn't great.

**Comment by musicEnfanthen** [comment]
I tested in an isolated repo, so... but yes, I rebase on develop.

**Comment by musicEnfanthen** [comment]
Superseded by #3668

**Pull request closed without merging**
