### PR TITLE
fix clef

### LINKED ISSUE #3181: Missing cases for octave-transposition clefs
15ma-down-treble clefs are being displayed instead as 8va-down-treble clefs:

Screen Shot 2022-12-23 at 3 35 17 PM

The top staff should have a 15 above the treble clef rather than an 8.

<details>
<summary> Click to view MEI data for above example </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title>Check octave displacements for treble clef</title>
         </titleStmt>
         <pubStmt />
      </fileDesc>
      <encodingDesc>
         <appInfo>
            <application isodate="2022-12-23T15:41:04" version="3.15.0-dev-6acd06e">
               <name>Verovio</name>
               <p>Transcoded from Humdrum</p>
            </application>
         </appInfo>
      </encodingDesc>
      <workList>
         <work>
            <title xml:id="title-L3" analog="humdrum:OTL" type="main">Check octave displacements for treble clef</title>
         </work>
      </workList>
      <extMeta>
         <frames xmlns="http://www.humdrum.org/ns/humxml">
            <metaFrame n="0" token="!!!OPR: Clef" xml:id="L1">
               <frameInfo>
                  <startTime float="0" />
                  <frameType>reference</frameType>
                  <referenceKey>OPR</referenceKey>
                  <referenceValue>Clef</referenceValue>
               </frameInfo>
            </metaFrame>
            <metaFrame n="1" token="!!!ONM: 6" xml:id="L2">
               <frameInfo>
                  <startTime float="0" />
                  <frameType>reference</frameType>
                  <referenceKey>ONM</referenceKey>
                  <referenceValue>6</referenceValue>
               </frameInfo>
            </metaFrame>
            <metaFrame n="2" token="!!!OTL: Check octave displacements for treble clef" xml:id="L3">
               <frameInfo>
                  <startTime float="0" />
                  <frameType>reference</frameType>
                  <referenceKey>OTL</referenceKey>
                  <referenceValue>Check octave displacements for treble clef</referenceValue>
               </frameInfo>
            </metaFrame>
            <metaFrame n="15" token="!!!title: @{OPR} @{ONM}: @{OTL}" xml:id="L16">
               <frameInfo>
                  <startTime float="4" />
                  <frameType>reference</frameType>
                  <referenceKey>title</referenceKey>
                  <referenceValue>@{OPR} @{ONM}: @{OTL}</referenceValue>
               </frameInfo>
            </metaFrame>
         </frames>
      </extMeta>
   </meiHead>
   <music>
      <body>
         <mdiv xml:id="m1hc08uc">
            <score xml:id="s1pnqrcr">
               <scoreDef xml:id="sgsgzqc" midi.bpm="400.000000">
                  <pgHead xml:id="p1e9uso8">
                     <rend xml:id="r14rh5qc" halign="center" valign="middle">
                        <rend xml:id="r166ioj6" fontsize="large">Check octave displacements for treble clef</rend>
                        <lb xml:id="l1dohd3k" /> 
<lb xml:id="l1u56k3e" /> </rend>
                  </pgHead>
                  <staffGrp xml:id="sh3kprz" symbol="bracket">
                     <staffDef xml:id="staffdef-L4F5" n="1" lines="5">
                        <clef xml:id="clef-L5F5" shape="G" line="2" dis="15" dis.place="above" />
                        <meterSig xml:id="metersig-L6F5" count="4" unit="4" />
                     </staffDef>
                     <staffDef xml:id="staffdef-L4F4" n="2" lines="5">
                        <clef xml:id="clef-L5F4" shape="G" line="2" dis="15" dis.place="below" />
                        <meterSig xml:id="metersig-L6F4" count="4" unit="4" />
                     </staffDef>
                     <staffDef xml:id="staffdef-L4F3" n="3" lines="5">
                        <clef xml:id="clef-L5F3" shape="G" line="2" dis="8" dis.place="above" />
                        <meterSig xml:id="metersig-L6F3" count="4" unit="4" />
                     </staffDef>
                     <staffDef xml:id="staffdef-L4F2" n="4" lines="5">
                        <clef xml:id="clef-L5F2" shape="G" line="2" dis="8" dis.place="below" />
                        <meterSig xml:id="metersig-L6F2" count="4" unit="4" />
                     </staffDef>
                     <staffDef xml:id="staffdef-L4F1" n="5" lines="5">
                        <clef xml:id="clef-L5F1" shape="G" line="2" />
                        <meterSig xml:id="metersig-L6F1" count="4" unit="4" />
                     </staffDef>
                  </staffGrp>
               </scoreDef>
               <section xml:id="section-L4F1">
                  <measure xml:id="measure-L1" n="1">
                     <staff xml:id="staff-L4F5" n="1">
                        <layer xml:id="layer-L1F5N1" n="1">
                           <note xml:id="note-L13F5" dur="1" oct="6" pname="g" accid.ges="n" />
                        </layer>
                     </staff>
                     <staff xml:id="staff-L4F4" n="2">
                        <layer xml:id="layer-L1F4N1" n="1">
                           <note xml:id="note-L13F4" dur="1" oct="2" pname="g" accid.ges="n" />
                        </layer>
                     </staff>
                     <staff xml:id="staff-L4F3" n="3">
                        <layer xml:id="layer-L1F3N1" n="1">
                           <note xml:id="note-L13F3" dur="1" oct="5" pname="g" accid.ges="n" />
                        </layer>
                     </staff>
                     <staff xml:id="staff-L4F2" n="4">
                        <layer xml:id="layer-L1F2N1" n="1">
                           <note xml:id="note-L13F2" dur="1" oct="3" pname="g" accid.ges="n" />
                        </layer>
                     </staff>
                     <staff xml:id="staff-L4F1" n="5">
                        <layer xml:id="layer-L1F1N1" n="1">
                           <note xml:id="note-L13F1" dur="1" oct="4" pname="g" accid.ges="n" />
                        </layer>
                     </staff>
                     <dir xml:id="dir-L12F5" place="below" staff="1" tstamp="1.000000">
                        <rend xml:id="r1s5m0mi" fontstyle="normal">display two octaves lower</rend>
                     </dir>
                     <dir xml:id="dir-L11F4" place="below" staff="2" tstamp="1.000000">
                        <rend xml:id="r11ou63f" fontstyle="normal">display two octaves higher</rend>
                     </dir>
                     <dir xml:id="dir-L10F3" place="below" staff="3" tstamp="1.000000">
                        <rend xml:id="rjt68vi" fontstyle="normal">display one octave lower</rend>
                     </dir>
                     <dir xml:id="dir-L9F2" place="below" staff="4" tstamp="1.000000">
                        <rend xml:id="rgbnsh0" fontstyle="normal">display one octave higher</rend>
                     </dir>
                     <dir xml:id="dir-L8F1" place="below" staff="5" tstamp="1.000000">
                        <rend xml:id="raupzjw" fontstyle="normal">normal treble clef</rend>
                     </dir>
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```

</details>

StaffDefs from MEI data (first one is correct, but `clef@dis="15" is displaying as `8`):

```xml
<staffDef xml:id="staffdef-L4F5" n="1" lines="5">
   <clef xml:id="clef-L5F5" shape="G" line="2" dis="15" dis.place="above" />
   <meterSig xml:id="metersig-L6F5" count="4" unit="4" />
</staffDef>
<staffDef xml:id="staffdef-L4F4" n="2" lines="5">
   <clef xml:id="clef-L5F4" shape="G" line="2" dis="15" dis.place="below" />
   <meterSig xml:id="metersig-L6F4" count="4" unit="4" />
</staffDef>
<staffDef xml:id="staffdef-L4F3" n="3" lines="5">
   <clef xml:id="clef-L5F3" shape="G" line="2" dis="8" dis.place="above" />
   <meterSig xml:id="metersig-L6F3" count="4" unit="4" />
</staffDef>
<staffDef xml:id="staffdef-L4F2" n="4" lines="5">
   <clef xml:id="clef-L5F2" shape="G" line="2" dis="8" dis.place="below" />
   <meterSig xml:id="metersig-L6F2" count="4" unit="4" />
</staffDef>
<staffDef xml:id="staffdef-L4F1" n="5" lines="5">
   <clef xml:id="clef-L5F1" shape="G" line="2" />
   <meterSig xml:id="metersig-L6F1" count="4" unit="4" />
</staffDef>
```

### PR DESCRIPTION
**Pull request by rettinghaus**
closes #3181

### CODE REVIEW

**Review by craigsapp — APPROVED** [review]
Looks great!  Now uses the correct SMuFL glyph for 15ma above G clef symbol.

http://www.smufl.org/version/latest/range/clefs
Screen Shot 2022-12-24 at 5 06 02 AM

**Comment by lpugin** [comment]
@rettinghaus could you rebase it?

**Comment by rettinghaus** [comment]
Why should that be done? It is based on the latest develop.

**Comment by lpugin** [comment]
Test suite is failing

**Comment by lpugin** [comment]
I will fix it

**Comment by lpugin** [comment]
It seems to be because https://smufl-browser.edirom.de/ is down. @peterstadler, any change to look at it?

**Comment by peterstadler** [comment]
https://smufl-browser.edirom.de/ is up again. Sorry for the annoyance but our university thought it to be more secure to block all traffic outside Europe until January 3rd. 🤦 So a lot of our automatic pipelines are currently failing …

**Comment by peterstadler** [comment]
https://smufl-browser.edirom.de/ should be reachable again from outside Europe. Please rerun the tests

**Pull request merged**
