### PR TITLE
Update Midifile library

### PR DESCRIPTION
**Pull request by rettinghaus**
This updates Craig Sapp's Midifile to latest revision.

### CODE REVIEW

**Review by craigsapp — APPROVED** [review]

**Comment by craigsapp** [comment]
Merge seems to have been done, but you added a commit (maybe after PR was merged) and I get a strange message:

Screenshot 2024-04-22 at 8 34 47 AM

but it looks like the code in the `master` branch has been updated:

```cpp
#define TIME_STATE_DELTA       0
#define TIME_STATE_ABSOLUTE    1

#define TRACK_STATE_SPLIT      0
#define TRACK_STATE_JOINED     1
```

**Comment by craigsapp** [comment]
Nevermind, I thought this was on the `midifile` repository.

**Comment by craigsapp** [comment]
For these strange reversions:

Screenshot 2024-04-22 at 2 57 24 PM

I think the problem is that they were added in the `verovio` repository instead of the `midifile` repository (so copying from `midifile` removed them).  I have added them in the `midifile` repository with commit https://github.com/craigsapp/midifile/commit/6ca59f8c0c5ad55200b3f8a5a287abe48efefcaa.

**Comment by rettinghaus** [comment]
@craigsapp I couldn't see these changes. However, I'm very happy with the updates and made it into a single commit now.

**Pull request merged**
