### PR TITLE
Code maintenance

### PR DESCRIPTION
**Pull request by rettinghaus**
This PR brings some minor code changes to js files static code checkers were complaining about. 
It also updates the iOS headers by running the included shell script. 

No changes in behaviour are expected.

### CODE REVIEW

**Comment by lpugin** [comment]
Out of curiosity: what is the problem with single quotes?

**Comment by craigsapp** [comment]
I would say nothing as they are interchangeable in javascript, but it does make C++ programmers happy :-)

**Comment by rettinghaus** [comment]
It's just to make Codacy happy. Like javascript I don't care too much (although I also have a slight preference to doublequotes).

**Comment by ahankinson** [comment]
If we're introducing these sorts of standards into the code base there should be some sort of shared configuration. Otherwise we're going to get lots of these little commits that just bring them into a "local" standard that is not shared by anyone else on the project.

**Comment by lpugin** [comment]
Consistency can be a justification for such changes, but just personal preferences cannot.

In any case, it would be good if such changes could be documented with more information in the PR / commits together with some coding guidelines and configurations where ever they apply.

**Pull request merged**
