### PR TITLE
Slur improvements

### PR DESCRIPTION
**Pull request by DavidBauer1984**
This PR does some improvements for slurs:

**1. Detached slurs**
We fix the regressions observed in #2730 and #2770 by reverting the changes in PR #2583. 
Fixed3
Fixed1
 @craigsapp Please check if #2418 should be reopened again. Note that due to recent changes in slur thickness the example doesn't look as ridiculous anymore.
Unfixed
However the directional problem (slur going down while notes going up) still persists. In retrospect it probably makes more sense to address this in the initial slur calculation instead of collision avoidance.

**2. Slurs moving outwards at end points**
We enforce that the slur direction at the end points is vertical in the worst case.
| Before | After |
| ------ | ----- |
| Before | After |

<details>
<summary> Show MEI example </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2022-03-25T05:47:52" version="3.8.0-dev-c01277e">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mu8bh4q">
    <score xml:id="s78qk69">
     <scoreDef xml:id="s62kb8i">
      <staffGrp xml:id="sqks0o8">
       <staffDef xml:id="sum0tzs" n="1" lines="5">
        <clef xml:id="cydwnv2" shape="G" line="2" />
        <meterSig xml:id="metersig-L2F1" count="4" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="spibhi9" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <beam xml:id="beam-L12F1-L13F1">
          <note xml:id="note-L12F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L13F1" type="placed" dur="16" oct="5" pname="g" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L14F1-L15F1">
          <note xml:id="note-L14F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L15F1" type="placed" dur="16" oct="5" pname="a" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L16F1-L17F1">
          <note xml:id="note-L16F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L17F1" type="placed" dur="16" oct="5" pname="b" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L18F1-L19F1">
          <note xml:id="note-L18F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L19F1" type="placed" dur="16" oct="6" pname="c" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L21F1-L22F1">
          <note xml:id="note-L21F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L22F1" type="placed" dur="16" oct="6" pname="d" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L23F1-L24F1">
          <note xml:id="note-L23F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L24F1" type="placed" dur="16" oct="6" pname="e" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L25F1-L26F1">
          <note xml:id="note-L25F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L26F1" type="placed" dur="16" oct="6" pname="f" stem.dir="down" accid.ges="n" />
         </beam>
         <beam xml:id="beam-L27F1-L28F1">
          <note xml:id="note-L27F1" type="placed" dur="16" oct="4" pname="b" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L28F1" type="placed" dur="16" oct="6" pname="g" stem.dir="down" accid.ges="n" />
         </beam>
        </layer>
       </staff>
       <slur xml:id="slur-L12F1-L13F1" staff="1" startid="#note-L12F1" endid="#note-L13F1" />
       <slur xml:id="slur-L14F1-L15F1" staff="1" startid="#note-L14F1" endid="#note-L15F1" />
       <slur xml:id="slur-L16F1-L17F1" staff="1" startid="#note-L16F1" endid="#note-L17F1" />
       <slur xml:id="slur-L18F1-L19F1" staff="1" startid="#note-L18F1" endid="#note-L19F1" />
       <slur xml:id="slur-L21F1-L22F1" staff="1" startid="#note-L21F1" endid="#note-L22F1" />
       <slur xml:id="slur-L23F1-L24F1" staff="1" startid="#note-L23F1" endid="#note-L24F1" />
       <slur xml:id="slur-L25F1-L26F1" staff="1" startid="#note-L25F1" endid="#note-L26F1" />
       <slur xml:id="slur-L27F1-L28F1" staff="1" startid="#note-L27F1" endid="#note-L28F1" />
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```
</details>

### CODE REVIEW

**Comment by craigsapp** [comment]
> We enforce that the slur direction at the end points is vertical in the worst case.

That is a tiny change, but it does seem to improve readability now that the start of the slurs point directly to the lower notehead.   Increasing the curvature a little bit more would help avoid the ending notehead and ledger lines.

> Note that due to recent changes in slur thickness the example doesn't look as ridiculous anymore.

Yes, it is much better so we can keep it closed for now.  Preferably if one slur is moved to the top of the stem, the other would as well.   Also the slurs are not symmetric for any particular reason.  Here is where I place them manually (with a more symmetric look):

Screen Shot 2022-04-07 at 6 46 01 AM

**Comment by DavidBauer1984** [comment]
> Also the slurs are not symmetric for any particular reason.

The asymmetry stems from the fact that there is an obstacle (flag / accidental) only on one side of the slur.

The initial slur is drawn like this:
Initial
Then collision avoidance kicks in and moves the front of the slur upwards, thus breaking symmetry.

We could address this by picking a different start/endpoint based on the presence of i.e. flags. Also could try to fix symmetry during shape adjustment at the very end. Anyway, this is a different issue and should be fixed in another PR.

@craigsapp I'll make a note, but feel free to open a separate issue for this.

**Comment by craigsapp** [comment]
In this sort of situation, the slur (Bezier curve) should be rotated.  What you are doing here is something different.  The initial slur control points are calculated correctly to get a symmetric slur.  Is there a way to recalculate the Bezier control points given the new endpoint based on the original placement algorithm?

**Comment by craigsapp** [comment]
You are moving the Bezier control points only vertically to adjust the slur, but there will need to be some horizontal motion of the control points as well when rotation is done.  Rotation will also fix the problem with the thickness of the slur.

If I were implementing rotation for this sort of case, I would first calculate the slur along the horizontal axis with the desired curvature and distance between the endpoints.   Then choose a rotation point (left, center point, or right side of the slur) to rotate to the desired angle, and then translation from the rotation point to the final position in the music.

(In other words I would throw away all control points and recalculate new ones)

**Comment by DavidBauer1984** [comment]
The problem is that any rigid motion (translation, rotation) will move the endpoints. In general this is bad since the whole point of the collision avoidance algorithm (see #2384) is to avoid collisions without moving the endpoints a lot. Also symmetrizing the slur with respect to its end points after collision avoidance only makes sense in certain cases. First of all, there is always the change of producing new collisions by symmetrisation. Second, there are cases where non-symmetric slurs are much better. Think of a example like this:
Non-symmetric
 
Anyway I have added consideration of flags during initial slur drawing as suggested in my previous post:
Example1
Example2

**Comment by craigsapp** [comment]
For this slur, I would put the peak of the slur over the highest note:

Screen Shot 2022-04-08 at 7 09 57 AM

The update (c) looks good:

Screen Shot 2022-04-08 at 7 34 27 AM


 Notice that it has the same shape as the original (a), as if it were a rotation of the original, but longer.  In particular the curvature at both ends of slurs (a) and (c) are the same.  Slur (b) does not have matching curvatures at each end, and the end highlighted in red is extremely objectionable.

**Comment by DavidBauer1984** [comment]
@lpugin Issues #2730 and #2770 can be closed.

**Pull request merged**
