### PR TITLE
Connect slurs to note heads instead of chords in MusicXML import

### PR DESCRIPTION
**Pull request by rettinghaus**

### CODE REVIEW

**Comment by lpugin** [comment]
Looks OK for me to attach slurs to notes. However, it is expected to yield a different rendering output - I have to check the implementation status of this. See https://github.com/rism-digital/verovio/issues/920#issuecomment-763618773
Will this what you expect?

**Comment by rettinghaus** [comment]
Most of the cases should look the same, if they are encoded correctly. But when you have chords with three notes and slurs there is no way to connect the slurs to chords in a way it would make sense.

**Comment by lpugin** [comment]
> Most of the cases should look the same, if they are encoded correctly. 

Sorry, I don't understand. The issue I referred to is showing that attaching slurs to notes and attaching slurs to chords should not look the same. For example, with a slur attached to the notes (one slur) you would expect this
image

With a slur attached to the chord this
image

> But when you have chords with three notes and slurs there is no way to connect the slurs to chords in a way it would make sense.

If a slur is connected to the chord, the number of notes it contains does not make any difference. So I don't understand this either.

**Comment by rettinghaus** [comment]
Ok, what I meant is if there are chords with more than two noteheads and every notehead has a slur. 
However, slurs in MusicXML are _always_ connected to noteheads and there is no way to figure out if actually the chord it belongs to is meant. No word whatsoever in the documentation. So for now I think this would be the better implementation.

**Pull request merged**
