### PR TITLE
Implement --mnum-interval for frequency of automatically placed measure numbers

### PR DESCRIPTION
**Pull request by earboxer**
see https://github.com/rism-digital/verovio/issues/1153#issuecomment-540940279

Examples

* `verovio --mnum-interval 1 file.mei` -- show every measure number
* `verovio --mnum-interval 10 file.mei` -- show every 10th measure number (like https://github.com/rism-digital/verovio/issues/1153#issuecomment-540050375)
* and with the value 0, it has the same behavior as master.

### CODE REVIEW

**Comment by rettinghaus** [comment]
I don't think that this is a sufficient solution. What if you have non-integral measure numbers like `10a` an `10b`?
And how would you turn off measure number display? To me a value of 0 would be the choice to achieve that, but that will keep the current behaviour?

**Comment by lpugin** [comment]
> And how would you turn off measure number display?

@rettinghaus you can do `<scoreDef mnum.visible="false">` or as you suggested https://github.com/rism-digital/verovio/issues/1153#issuecomment-538128676 use css.

Another approach would be to have `-1` as default yielding the current behaviour (meaning beginning of each system), and turn off measure number display when `0` is set. However, this is not very intuitive and would require to be well documented.

**Comment by earboxer** [comment]
@rettinghaus In this implementation, as `std::atoi` will treat both "10a" and "10b" as 10, both would appear (for mnumInterval of 2, 5, or 10).
If you want to show every 10th measure number, you'd need to manually tell 10b to not show the measure number. This can be done by adding an empty mNum.

```xml
<measure n="9"></measure>
<measure n="10a"></measure>
<measure n="10b"><mNum></mNum></measure>
<measure n="11"></measure>
```

With `verovio --mnum-interval 10 file.mei`, you'd get "10a", "20", "30"...

**Comment by lpugin** [comment]
Looks good to me as a start

**Pull request merged**
