### PR TITLE
Stem length issues

### LINKED ISSUE #1963: beam stem-length problem
Here is an example of a problem calculating the length of stems for beamed notes:

Screen Shot 2021-01-16 at 7 31 36 PM

The second measure is rendered correctly, but the beam in the first measure is too high.

MEI data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2021-01-16T19:31:38" version="3.1.0-dev-0361cac-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000000704076145">
    <score xml:id="score-0000000484524934">
     <scoreDef xml:id="scoredef-0000001958000954">
      <staffGrp xml:id="staffgrp-0000002089511853">
       <staffDef xml:id="staffdef-0000001688578438" n="1" lines="5">
        <clef xml:id="clef-L2F1" shape="G" line="2" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1">
       <staff xml:id="staff-0000000112745028" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L3F1" type="placed" dur="8" oct="5" pname="f" stem.dir="up" accid.ges="n" />
         <beam xml:id="beam-L4F1-L5F1">
          <note xml:id="note-L4F1" type="placed" dur="8" oct="5" pname="f" stem.dir="up" accid.ges="n" />
          <note xml:id="note-L5F1" type="placed" dur="8" oct="5" pname="g" stem.dir="up" accid.ges="n" />
         </beam>
         <note xml:id="note-L6F1" type="placed" dur="8" oct="5" pname="g" stem.dir="up" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L7">
       <staff xml:id="staff-L7F1N1" n="1">
        <layer xml:id="layer-L7F1N1" n="1">
         <note xml:id="note-L8F1" type="placed" dur="8" oct="4" pname="e" stem.dir="down" accid.ges="n" />
         <beam xml:id="beam-L9F1-L10F1">
          <note xml:id="note-L9F1" type="placed" dur="8" oct="4" pname="e" stem.dir="down" accid.ges="n" />
          <note xml:id="note-L10F1" type="placed" dur="8" oct="4" pname="d" stem.dir="down" accid.ges="n" />
         </beam>
         <note xml:id="note-L11F1" type="placed" dur="8" oct="4" pname="d" stem.dir="down" accid.ges="n" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

### PR DESCRIPTION
**Pull request by DavidBauer1984**
Fixes #1963 and #2004

### CODE REVIEW

**Comment by DavidBauer1984** [comment]
During debugging I noted that line 1274 in beam.cpp

`const bool onStaffLine = m_closestNote->GetDrawingLoc() % 2;`

seems to be wrong. The note is actually on the staff line for even drawing locations. Should I fix this too?

**Comment by lpugin** [comment]
> Should I fix this too?

Yes please

**Comment by lpugin** [comment]
Unfortunately, the latest fix introduces many changes that do not look good to me - not surprisingly. See the test suite before
https://github.com/rism-digital/verovio/suites/2527298016/artifacts/54771598
and after:
https://github.com/rism-digital/verovio/suites/2533128167/artifacts/54946917

For example:

image

So if the statement is wrong, then we also need to correct its handling of it which must also be wrong... What do you want to do?

**Comment by DavidBauer1984** [comment]
You are right, this is bad. I went back to the previous version and renamed the variable. Thus the functionality is not affected and the code now looks right.

**Pull request merged**
