### PR TITLE
Improve beam notehead collision

### PR DESCRIPTION
**Pull request by Monceber**
Improved beam positioning to avoid collisions with noteheads in multi-layer situations.
If there might be overlapping elements on the other layers we do not shorten beam stems in that duration, if that's enough to avoid collision. Otherwise, we get additional offset for the beam, to avoid said elements.
Before:
image

After:
image

### CODE REVIEW

**Comment by ahankinson** [comment]
It looks like this has some regressions in the cross-staff tests...

**Comment by lpugin** [comment]
Thanks!

**Comment by lpugin** [comment]
Could we have the example added to the test suite in `layer`?

**Comment by rettinghaus** [comment]
@lpugin I'll add it.

**Pull request merged**
