### PR TITLE
fix: make c4 as default for neume notation

### PR DESCRIPTION
**Pull request by yinanazhou**
refs: https://github.com/DDMAL/Neon/issues/1241

### CODE REVIEW

**Comment by lpugin** [comment]
This is how [this](https://github.com/rism-digital/verovio.org/blob/gh-pages/_tests/neume/neume-002.mei) file looks before and after:

image

I think you are changing the default octave for the C clef, which is not that same as making C4 the default.

**Comment by yinanazhou** [comment]
This is expected. The test file is outdated as it uses C3 as default. I will update it.

**Comment by lpugin** [comment]
OK, thanks. I think you also need to update [neume-001](https://github.com/rism-digital/verovio.org/blob/gh-pages/_tests/neume/neume-001.mei) (from the sixth staff)

**Comment by lpugin** [comment]
Merging following discussion with @yinanazhou. The test file will be updated.

**Pull request merged**
