### PR TITLE
Implement support for extended MeterSig symbols

### PR DESCRIPTION
**Pull request by Monceber**
Updated libMEI and added support for the MeterSig count values, that contain symbols `\`, `*` and `-`.
image

### CODE REVIEW

**Review by lpugin — COMMENTED** [review]
I am not convinced to store `MeterSig::m_count` as a string. Applying a regex every time `MeterSig::GetTotalCount` is called through its call to `Meter::GetMeterCounts()` does not look very efficient and a step back. Can you think of a way to avoid this?

**Comment by Monceber** [comment]
@lpugin I've changed code to cache calculated values, so regex will be used only on the first call. On all other subsequent call we'll use stored value instead.

**Comment by lpugin** [comment]
Yes, that is better. However, thinking about it it seems to me that having a
 ```cpp
typedef std::pair<std::vector<int>, MeterCountSign> data_METERCOUNT_pair
```
and do the splitting / reassembly in 
```cpp
std::string Att::MetercountPairToStr(data_METERCOUNT_pair data) const;
data_METERCOUNT_pair StrToMetercountPair(std::string value) const;
```
would be more inline with what we have elsewhere.

It would also avoid possible side effects with the cache not being reset when the `m_count` value changes.

What do you think?

**Comment by Monceber** [comment]
Yes, I guess that would make code cleaner and closer to what we have now.
I was avoiding doing changes to the generated LibMEI code since that is going to be changed some day.
We might just as well ignore changes to the file how we did this previously. but with schema changes at some point we'd have to address it anyway.

I guess, if you're okay with changing generated parts of the code then I'll move my changes there, that would indeed solve this problem.

**Pull request merged**
