### PR TITLE
Improve tuplet number positioning with angled beams

### PR DESCRIPTION
**Pull request by Monceber**
Adjusted positioning for the tuplet numbers, so that they are placed closer to the beams, instead of putting them at the highest position of the beam. Adjusted positioning for the dynamics in the similar fashion.

Previous rendering:
image

New rendering:
image

<details><summary>MEI:</summary>

```XML
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title />
            <respStmt />
         </titleStmt>
         <pubStmt>
            <date isodate="2021-05-04" type="encoding-date">2021-05-04</date>
         </pubStmt>
      </fileDesc>
      <encodingDesc xml:id="encodingdesc-0000000000012087">
         <appInfo xml:id="appinfo-0000000000027307">
            <application xml:id="application-0000000000005034" isodate="2021-06-09T17:58:28" version="3.5.0-dev-[undefined]">
               <name xml:id="name-0000000000014984">Verovio</name>
               <p xml:id="p-0000000000001165">Transcoded from MusicXML</p>
            </application>
         </appInfo>
      </encodingDesc>
   </meiHead>
   <music>
      <body>
         <mdiv xml:id="mdiv-0000000000015890">
            <score xml:id="score-0000000000004211">
               <scoreDef xml:id="scoredef-0000000000007233">
                  <staffGrp xml:id="staffgrp-0000000000017405">
                     <staffDef xml:id="P1" n="1" lines="5" ppq="24">
                        <label xml:id="label-0000000000031254">Piano</label>
                        <labelAbbr xml:id="labelAbbr-0000000000006313">Pno.</labelAbbr>
                        <instrDef xml:id="instrdef-0000000000019550" midi.channel="0" midi.instrnum="0" midi.volume="78.00%" />
                        <clef xml:id="clef-0000000000015451" shape="F" line="4" />
                        <keySig xml:id="keysig-0000000000023074" sig="5f" />
                        <meterSig xml:id="msig-0000000000022983" count="4" unit="4" />
                     </staffDef>
                  </staffGrp>
               </scoreDef>
               <section xml:id="section-0000000000002931">
                  <pb xml:id="pb-0000000000014139" />
                  <measure xml:id="measure-64-mdiv-1" n="3">
                     <staff xml:id="staff-0000000000021565" n="1">
                        <layer xml:id="layer-0000000000004401" n="1">
                           <beam xml:id="beam-0000000000005294">
                              <tuplet xml:id="tuplet-0000000000025435" num="6" numbase="4" num.format="count">
                                 <note xml:id="note-0101-10110-12720-1" dur.ppq="4" dur="16" oct="2" pname="e" stem.dir="up" accid.ges="f" />
                                 <note xml:id="note-0101-10160-12680-1" dur.ppq="4" dur="16" oct="2" pname="b" stem.dir="up" accid.ges="f" />
                                 <note xml:id="note-0101-10200-12650-1" dur.ppq="4" dur="16" oct="3" pname="e" stem.dir="up" accid.ges="f" />
                                 <note xml:id="note-0101-10250-12630-1" dur.ppq="4" dur="16" oct="3" pname="b" stem.dir="up" accid.ges="f" />
                                 <note xml:id="note-0101-10290-12610-1" dur.ppq="4" dur="16" oct="4" pname="e" stem.dir="up" accid.ges="f" />
                                 <note xml:id="note-0101-10340-12580-1" dur.ppq="4" dur="16" oct="4" pname="a" stem.dir="up" accid.ges="f" />
                              </tuplet>
                           </beam>
                           <note xml:id="note-0101-10380-12560-1" dur.ppq="24" dur="4" oct="4" pname="g" stem.dir="up" accid.ges="f">
                              <artic xml:id="artic-0000000000007299" artic="ten" place="above" />
                           </note>
                           <beam xml:id="beam-0000000000020044">
                              <tuplet xml:id="tuplet-0000000000024937" num="6" numbase="4" num.format="count">
                                 <note xml:id="note-0101-10560-12760-1" dur.ppq="4" dur="16" oct="1" pname="a" stem.dir="up" accid.ges="f">
                                    <artic xml:id="artic-0000000000007005" artic="acc" place="below" />
                                 </note>
                                 <note xml:id="note-0101-10610-12690-1" dur.ppq="4" dur="16" oct="2" pname="a" stem.dir="up" accid.ges="f" />
                                 <note xml:id="note-0101-10650-12650-1" dur.ppq="4" dur="16" oct="3" pname="e" stem.dir="up" accid.ges="f" />
                                 <note xml:id="note-0101-10700-12620-1" dur.ppq="4" dur="16" oct="3" pname="a" stem.dir="up" accid.ges="f" />
                                 <note xml:id="note-0101-10740-12600-1" dur.ppq="4" dur="16" oct="4" pname="c" stem.dir="up" />
                                 <note xml:id="note-0101-10780-12580-1" dur.ppq="4" dur="16" oct="4" pname="e" stem.dir="up" accid.ges="f" />
                              </tuplet>
                           </beam>
                           <clef xml:id="clef-49" shape="F" line="4" />
                           <beam xml:id="beam-0000000000021707">
                              <note xml:id="note-0101-10850-12680-1" dur.ppq="12" dur="8" oct="4" pname="g" stem.dir="up" accid.ges="f" />
                              <note xml:id="note-0101-10940-12670-1" dur.ppq="12" dur="8" oct="4" pname="a" stem.dir="up" accid.ges="f" />
                           </beam>
                        </layer>
                     </staff>
                     <dynam place="above" staff="1" tstamp="1.25000">f</dynam>
                     <dynam place="above" staff="1" tstamp="1.75000">f</dynam>
                  </measure>
                  <measure xml:id="measure-11-mdiv-1" n="4">
                     <staff xml:id="staff-0000000000018732" n="1">
                        <layer xml:id="layer-0000000000005998" n="1">
                           <beam xml:id="beam-0000000000031164">
                              <tuplet xml:id="tuplet-0000000000027153" num="6" numbase="4" num.format="count" num.place="below">
                                 <note xml:id="note-0097-10670-11870-2" dur.ppq="4" dur="16" oct="2" pname="a" stem.dir="up">
                                    <accid xml:id="accid-0000000000015420" accid="n" accid.ges="n" />
                                 </note>
                                 <note xml:id="note-0097-10730-11860-2" dur.ppq="4" dur="16" oct="2" pname="b" stem.dir="up">
                                    <accid xml:id="accid-0000000000002730" accid="n" accid.ges="n" />
                                 </note>
                                 <note xml:id="note-0097-10780-11840-2" dur.ppq="4" dur="16" oct="3" pname="c" stem.dir="up">
                                    <accid xml:id="accid-0000000000001257" accid="n" accid.ges="n" />
                                 </note>
                                 <note xml:id="note-0097-10490-11960-2" dur.ppq="4" dur="16" oct="3" pname="d" stem.dir="up">
                                    <accid xml:id="accid-0000000000024876" accid="n" accid.ges="n" />
                                 </note>
                                 <note xml:id="note-0097-10550-11920-2" dur.ppq="4" dur="16" oct="3" pname="e" stem.dir="up">
                                    <accid xml:id="accid-0000000000021813" accid="n" accid.ges="n" />
                                 </note>
                                 <note xml:id="note-0097-10610-11890-2" dur.ppq="4" dur="16" oct="3" pname="f" stem.dir="up">
                                    <accid xml:id="accid-0000000000021375" accid="n" accid.ges="n" />
                                 </note>
                              </tuplet>
                           </beam>
                           <beam xml:id="beam-0000000000014726">
                              <note xml:id="note-0097-10830-11840-2" dots="1" dur.ppq="9" dur="16" oct="4" pname="f" stem.dir="down" />
                              <note xml:id="note-0097-10910-11820-2" dur.ppq="3" dur="32" oct="4" pname="g" stem.dir="down">
                                 <accid xml:id="accid-0000000000017230" accid="n" accid.ges="n" />
                              </note>
                              <note xml:id="note-0097-10940-11840-2" dur.ppq="12" dur="8" oct="4" pname="f" stem.dir="down" />
                           </beam>
                           <beam xml:id="beam-0000000000004557">
                              <tuplet xml:id="tuplet-0000000000019387" num="6" numbase="4" num.format="count">
                                 <note xml:id="note-0097-11010-11960-2" dur.ppq="4" dur="16" oct="2" pname="g" stem.dir="down" accid.ges="n" />
                                 <note xml:id="note-0097-11050-11920-2" dur.ppq="4" dur="16" oct="3" pname="d" stem.dir="down" accid.ges="n" />
                                 <note xml:id="note-0097-11090-11890-2" dur.ppq="4" dur="16" oct="3" pname="g" stem.dir="down" accid.ges="n" />
                                 <note xml:id="note-0097-11130-11870-2" dur.ppq="4" dur="16" oct="3" pname="b" stem.dir="down" accid.ges="n" />
                                 <note xml:id="note-0097-11170-11860-2" dur.ppq="4" dur="16" oct="4" pname="d" stem.dir="down" accid.ges="n" />
                                 <note xml:id="note-0097-11210-11850-2" dur.ppq="4" dur="16" oct="4" pname="e" stem.dir="down" accid.ges="n" />
                              </tuplet>
                           </beam>
                           <beam xml:id="beam-0000000000000995">
                              <note xml:id="note-0097-11250-11840-2" dur.ppq="6" dur="16" oct="4" pname="f" stem.dir="down" />
                              <note xml:id="note-0097-11330-11830-2" dur.ppq="6" dur="16" oct="4" pname="g" stem.dir="down" accid.ges="n" />
                              <note xml:id="note-0097-11390-11840-2" dur.ppq="12" dur="8" oct="4" pname="f" stem.dir="down" />
                           </beam>
                        </layer>
                     </staff>
                     <dynam xml:id="dynam-L21F3" place="below" staff="1" tstamp="3.750000">f</dynam>
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```

</details>

### CODE REVIEW

**Review by lpugin — CHANGES_REQUESTED** [review]
Looks pretty good, thanks!

Just check accid-006
image

Can you confirm that the change tuplet-018 (first two tuplets with stem up) is intended?
image

**Comment by Monceber** [comment]
Regarding tuplet-018 - yes, it's intended. This way distance is decreased as far as possible, without placing whole number on the staff:
image

**Comment by Monceber** [comment]
Should be fixed now:
image

**Review by lpugin — APPROVED** [review]

**Comment by lpugin** [comment]
Thanks! Please add the example to the test suite, a good one to have.

**Comment by craigsapp** [comment]
> Regarding tuplet-018 - yes, it's intended. This way distance is decreased as far as possible, without placing whole number on the staff:

There is an exception to this rule when dealing with layers, and the tuplet number should be "inside" the staff rather than on the other side of the staff from the notes:

Screen Shot 2021-07-09 at 6 43 09 AM

The tuplet numbers are very readable, but their meaning is difficult to interpret since they are so far away from the noteheads.  So in this case the music as a whole is more readable if the tuplet numbers are not as readable by being moved off of the staff lines.

<details>
<summary>
Click to view MEI data for above example.
</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2021-07-09T06:44:00" version="3.5.0-dev-cfdb185">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000001185263358">
    <score xml:id="score-0000001610907713">
     <scoreDef xml:id="scoredef-0000001595807357">
      <staffGrp xml:id="staffgrp-0000001450950706">
       <staffDef xml:id="staffdef-0000001531221775" n="1" lines="5">
        <clef xml:id="clef-0000001357439789" shape="G" line="2" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1">
       <staff xml:id="staff-0000000066615023" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <tuplet xml:id="tuplet-L4F1-L6F1" num="3" numbase="2" bracket.place="below" bracket.visible="false" num.format="count">
          <beam xml:id="beam-L4F1-L6F1">
           <note xml:id="note-L4F1" type="placed" dur="8" oct="5" pname="f" stem.dir="up" accid.ges="n" />
           <note xml:id="note-L5F1" dur="8" oct="5" pname="g" accid.ges="n" />
           <note xml:id="note-L6F1" dur="8" oct="5" pname="f" accid.ges="n" />
          </beam>
         </tuplet>
         <tuplet xml:id="tuplet-L8F1-L10F1" num="3" numbase="2" bracket.place="below" bracket.visible="false" num.format="count">
          <beam xml:id="beam-L8F1-L10F1">
           <note xml:id="note-L8F1" dur="8" oct="5" pname="g" accid.ges="n" />
           <note xml:id="note-L9F1" dur="8" oct="5" pname="f" accid.ges="n" />
           <note xml:id="note-L10F1" dur="8" oct="5" pname="g" accid.ges="n" />
          </beam>
         </tuplet>
         <tuplet xml:id="tuplet-L12F1-L14F1" num="3" numbase="2" bracket.place="below" bracket.visible="false" num.format="count">
          <beam xml:id="beam-L12F1-L14F1">
           <note xml:id="note-L12F1" dur="8" oct="5" pname="f" accid.ges="n" />
           <note xml:id="note-L13F1" dur="8" oct="5" pname="e" accid.ges="n" />
           <note xml:id="note-L14F1" dur="8" oct="5" pname="f" accid.ges="n" />
          </beam>
         </tuplet>
         <tuplet xml:id="tuplet-L16F1-L18F1" num="3" numbase="2" bracket.place="below" bracket.visible="false" num.format="count">
          <beam xml:id="beam-L16F1-L18F1">
           <note xml:id="note-L16F1" dur="8" oct="5" pname="e" accid.ges="n" />
           <note xml:id="note-L17F1" dur="8" oct="5" pname="d" accid.ges="n" />
           <note xml:id="note-L18F1" dur="8" oct="5" pname="e" accid.ges="n" />
          </beam>
         </tuplet>
        </layer>
        <layer xml:id="layer-L4F2N2" n="2">
         <note xml:id="note-L4F2" dur="1" oct="4" pname="f" accid.ges="n" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</summary>

**Comment by rettinghaus** [comment]
"No human being would stack tuplets like this."

**Pull request merged**
