### PR TITLE
Fix Xcode build with humdrum scheme

### PR DESCRIPTION
**Pull request by DavidBauer1984**
This PR properly adds `graphic.h/cpp` to the Verovio Xcode project.

### CODE REVIEW

**Comment by rettinghaus** [comment]
Seems to address the same as #3085

**Comment by ahankinson** [comment]
Yes, I will merge #3085 and close this one.

**Comment by ahankinson** [comment]
They're basically the same except for ` settings = {ATTRIBUTES = (Public, ); }; };` -- is this necessary?

**Comment by DavidBauer1984** [comment]
> They're basically the same except for ` settings = {ATTRIBUTES = (Public, ); }; };` -- is this necessary?

No idea, but we use this setting for all other header files. So I usually include it, to keep things consistent.

**Comment by rettinghaus** [comment]
I just noticed that the header file is in the wrong place. I'll open another PR in some minutes.

**Pull request closed without merging**
