### PR TITLE
Humdrum reader: ottava fixes

### PR DESCRIPTION
**Pull request by gregchapman-dev**
1. Don't start an ottava twice (it will nuke the first one).
2. Add getStartIdForOttava, that works somewhat like getEndIdForOttava.  This picks up ottava start notes that are hidden because of a voice split between the ottava start mark and the first notes in the ottava, much like getEndIdForOttava does for ottava end notes that are hidden because of a voice merge between the last notes in the ottava and the ottava end mark.

### CODE REVIEW

**Comment by gregchapman-dev** [comment]
Here is a test case for getStartIdForOttava (the ottava in the right hand is the one that starts incorrectly without this fix):

[DifficultOttavas.krn.txt](https://github.com/user-attachments/files/15959531/DifficultOttavas.krn.txt)

**Comment by gregchapman-dev** [comment]
@craigsapp what do you think?

**Comment by craigsapp** [comment]
Looks great to me.   I will commit it and check in more detail.

Before the PR, the test data renders as:

Screenshot 2024-06-30 at 21 34 50

where the top line is improperly delayed by an eighth note.

**Comment by craigsapp** [comment]
PR fixes test case:

Screenshot 2024-06-30 at 21 58 18

Ideally the octave line end in the bottom staff would not touch the final barline...

**Review by craigsapp — COMMENTED** [review]
Looks great

**Pull request merged**
