### PR TITLE
Enclose for arpeggio and clefs

### PR DESCRIPTION
**Pull request by DavidBauer1984**
This PR implements the drawing of enclosing brackets and boxes for arpeggio and clefs.

| Arpeggio | Clefs |
| --------- | ----- |
| Arpeg | Clef |

<details>
  <summary>MEI for arpeggio</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title>Broken arpeggios</title>
         </titleStmt>
         <pubStmt>
            <respStmt>
               <persName role="encoder">Klaus Rettinghaus</persName>
               <corpName role="funder">Enote GmbH</corpName>
            </respStmt>
            <date isodate="2021-05-21">2021-05-21</date>
         </pubStmt>
         <notesStmt>
            <annot>
               <p>A broken arpeggio, in which both hands arpeggiate simultaneously, has a separate arpeggio sign for each hand and, if included, an arrow for each sign.</p>
            </annot>
         </notesStmt>
         <sourceDesc>
            <source>
               <bibl>Behind Bars, p. 132, example 2a</bibl>
            </source>
         </sourceDesc>
      </fileDesc>
      <encodingDesc>
         <appInfo>
            <application version="2.0.0" label="2">
               <name>Verovio</name>
            </application>
         </appInfo>
      </encodingDesc>
   </meiHead>
   <music>
      <body>
         <mdiv>
            <score>
               <scoreDef>
                  <staffGrp bar.thru="true">
                     <staffDef n="1" lines="5" ppq="1">
                        <clef shape="G" line="2" />
                        <keySig sig="0" />
                        <meterSig count="2" unit="4" form="invis" />
                     </staffDef>
                     <staffDef n="2" lines="5" ppq="1">
                        <clef shape="F" line="4" />
                        <keySig sig="0" />
                        <meterSig count="2" unit="4" form="invis" />
                     </staffDef>
                     <grpSym symbol="brace" />
                  </staffGrp>
               </scoreDef>
               <section>
                  <measure>
                     <staff n="1">
                        <layer n="1">
                           <chord xml:id="ex_1179776871" dur="2">
                              <note xml:id="ex_0407027738" oct="4" pname="e" />
                              <note xml:id="ex_0244395599" oct="4" pname="a" />
                              <note xml:id="ex_1568099329" oct="5" pname="c" />
                           </chord>
                        </layer>
                     </staff>
                     <staff n="2">
                        <layer n="5">
                           <chord xml:id="ex_1552330911" dur="2">
                              <note xml:id="ex_0698883822" oct="2" pname="a" />
                              <note xml:id="ex_0246793774" oct="3" pname="e" />
                              <note xml:id="ex_1072037261" oct="3" pname="a" />
                           </chord>
                        </layer>
                     </staff>
                     <arpeg plist="#ex_1179776871" enclose="brack" />
                     <arpeg plist="#ex_1552330911" enclose="brack" />
                  </measure>
                  <measure>
                     <staff n="1">
                        <layer n="1">
                           <chord xml:id="ex_1453522232" dur="2">
                              <note xml:id="ex_1357676401" oct="4" pname="e" />
                              <note xml:id="ex_0889483715" oct="4" pname="a" />
                              <note xml:id="ex_0919131238" oct="5" pname="c" />
                           </chord>
                        </layer>
                     </staff>
                     <staff n="2">
                        <layer n="5">
                           <chord xml:id="ex_0490720989" dur="2">
                              <note xml:id="ex_0128441232" oct="2" pname="a" />
                              <note xml:id="ex_1210457643" oct="3" pname="e" />
                              <note xml:id="ex_1049017870" oct="3" pname="a" />
                           </chord>
                        </layer>
                     </staff>
                     <arpeg plist="#ex_1453522232" order="down" arrow="true" enclose="brack" />
                     <arpeg plist="#ex_0490720989" order="down" arrow="true" enclose="brack" />
                  </measure>
                  <measure>
                     <staff n="1">
                        <layer n="1">
                           <chord xml:id="ex_1604003173" dur="4">
                              <note xml:id="ex_0907540481" oct="4" pname="e" />
                              <note xml:id="ex_1183350314" oct="4" pname="a" />
                              <note xml:id="ex_0722672531" oct="5" pname="c" />
                           </chord>
                           <chord xml:id="ex_0600358557" dur="4">
                              <note xml:id="ex_1937204732" oct="4" pname="e" />
                              <note xml:id="ex_1461583801" oct="4" pname="a" />
                              <note xml:id="ex_1920989021" oct="5" pname="c" />
                           </chord>
                        </layer>
                     </staff>
                     <staff n="2">
                        <layer n="5">
                           <chord xml:id="ex_0313159917" dur="4">
                              <note xml:id="ex_1867551267" oct="2" pname="a" />
                              <note xml:id="ex_1943789869" oct="3" pname="e" />
                              <note xml:id="ex_1755090119" oct="3" pname="a" />
                           </chord>
                           <chord xml:id="ex_0526533847" dur="4">
                              <note xml:id="ex_2111738488" oct="2" pname="a" />
                              <note xml:id="ex_1821740889" oct="3" pname="e" />
                              <note xml:id="ex_1324766144" oct="3" pname="a" />
                           </chord>
                        </layer>
                     </staff>
                     <arpeg plist="#ex_1604003173" order="up" arrow="true" enclose="brack" />
                     <arpeg plist="#ex_0313159917" order="down" arrow="true" enclose="brack" />
                     <arpeg plist="#ex_0600358557" order="down" arrow="true" enclose="brack" />
                     <arpeg plist="#ex_0526533847" order="up" arrow="true" enclose="brack" />
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```
</details>

<details>
  <summary>MEI for clefs</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title>Clef change example</title>
         </titleStmt>
         <pubStmt>
            <date isodate="2017-05-04">2017-05-04</date>
         </pubStmt>
         <seriesStmt>
            <title>Verovio test suite</title>
         </seriesStmt>
         <notesStmt>
            <annot>Verovio renders intermediate clef changes encoded with "clef" elements.</annot>
         </notesStmt>
      </fileDesc>
      <encodingDesc>
         <appInfo>
            <application version="2.0.0" label="2">
               <name>Verovio</name>
            </application>
         </appInfo>
      </encodingDesc>
   </meiHead>
   <music>
      <body>
         <mdiv>
            <score>
               <scoreDef>
                  <staffGrp symbol="bracket">
                     <staffDef n="1" lines="5" clef.shape="G" clef.line="2" key.sig="2s" meter.count="3" meter.unit="4" />
                     <staffDef n="2" lines="5" clef.shape="G" clef.line="2" key.sig="2s" meter.count="3" meter.unit="4" />
                  </staffGrp>
               </scoreDef>
               <section>
                  <measure n="5">
                     <staff n="1">
                        <layer n="1">
                           <chord dur="4" stem.dir="down">
                              <note oct="6" pname="d" />
                              <note oct="5" pname="b" />
                              <note oct="5" pname="g">
                                 <accid accid="s" />
                              </note>
                              <note oct="5" pname="e" />
                           </chord>
                           <rest dur="8" />
                           <note dur="8" oct="6" pname="c" stem.dir="down" accid.ges="s" />
                        </layer>
                     </staff>
                     <staff n="2">
                        <layer n="1">
                           <chord dur="4" stem.dir="up">
                              <note oct="4" pname="g">
                                 <accid accid="s" />
                              </note>
                              <note oct="3" pname="b" />
                           </chord>
                           <rest dur="8" />
                           <chord dur="8" stem.dir="up">
                              <note oct="4" pname="a" />
                              <note oct="3" pname="a" />
                           </chord>
                        </layer>
                     </staff>
                     <dynam place="below" staff="1" tstamp="1.000000">fz</dynam>
                  </measure>
                  <measure n="6">
                     <staff n="1">
                        <layer n="1">
                           <beam>
                              <note dur="8" oct="5" pname="b" stem.dir="down" />
                              <note dur="8" oct="6" pname="d" stem.dir="down" />
                           </beam>
                           <beam>
                              <note dur="8" oct="5" pname="e" stem.dir="down" />
                              <chord dur="8" stem.dir="down">
                                 <note oct="5" pname="g">
                                    <accid accid="s" />
                                 </note>
                                 <note oct="5" pname="d">
                                    <accid accid="n" />
                                 </note>
                              </chord>
                           </beam>
                        </layer>
                     </staff>
                     <staff n="2">
                        <layer n="1" label="feature-example">
                           <chord dur="8" stem.dir="up">
                              <note oct="4" pname="f" accid.ges="s" />
                              <note oct="4" pname="d" />
                           </chord>
                           <rest dur="8" />
                           <clef shape="F" line="4" enclose="box" />
                           <chord dur="8" stem.dir="down">
                              <note oct="4" pname="e" />
                              <note oct="3" pname="e" />
                           </chord>
                           <clef shape="C" line="3" enclose="box" />
                           <rest dur="8" />
                           <clef shape="G" line="2" enclose="box" />
                        </layer>
                     </staff>
                     <!--slur startid="n1" endid="n2" /-->
                  </measure>
                  <measure n="7">
                     <staff n="1">
                        <layer n="1">
                           <chord dur="4" stem.dir="down">
                              <note oct="5" pname="a" />
                              <note oct="5" pname="c" accid.ges="s" />
                           </chord>
                           <rest dur="8" />
                           <note dur="8" oct="5" pname="e" stem.dir="down" />
                        </layer>
                     </staff>
                     <staff n="2">
                        <layer n="1">
                           <beam>
                              <note dur="16" oct="3" pname="a" stem.dir="up" />
                              <note dur="16" oct="4" pname="a" stem.dir="up" />
                              <note dur="16" oct="4" pname="g" stem.dir="up">
                                 <accid accid="s" />
                              </note>
                              <note dur="16" oct="4" pname="a" stem.dir="up" />
                           </beam>
                           <beam>
                              <note dur="16" oct="4" pname="c" stem.dir="up" accid.ges="s" />
                              <note dur="16" oct="4" pname="a" stem.dir="up" />
                              <note dur="16" oct="4" pname="g" stem.dir="up" accid.ges="s" />
                              <note dur="16" oct="4" pname="a" stem.dir="up" />
                           </beam>
                        </layer>
                     </staff>
                     <!--slur startid="n3" endid="n4"/-->
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```
</details>

### CODE REVIEW

**Comment by lpugin** [comment]
Looks pretty good! I am sure you noticed it, and I assume it is because of the arrow, but would it be possible to have these two [] look the same? 
image

**Comment by DavidBauer1984** [comment]
This problem is related to how the arpeggio is drawn itself. The glyph widths for arpeggio arrows seem not right for some fonts (Leipzig in this case). I'm not sure if this should be corrected within the glyphs or in `View::DrawSmuflLine`. This perturbs the calculation of the number of filling glyphs and results in arpeggios drawn outside the given interval `[x, x + length]`. When drawing brackets and boxes I have to reserve extra vertical space if arrows are present because of this problem.

**Comment by rettinghaus** [comment]
I just checked SMuFL and this is indeed a Leipzig problem. I will fix those glyphs.

**Comment by rettinghaus** [comment]
With fixed glyphs:
arpeg-006

**Comment by DavidBauer1984** [comment]
I've updated the picture and inserted the (horizontal!) adjustment due to arrows again. Brackets and boxes should be drawn wider for wider arrows.

**Pull request merged**
