### PR TITLE
Pedal lines over system break

### LINKED ISSUE #1575: Pedal line up/down pairing ignores staff@n
The matching logic for pedal lines is flawed right now.

grafik

Rendering flaws:

* There should be a pedal line from bar 1 to bar 2 in all staves. It seems Verovio only supports having one single "active" pedal mark at a time. The first three `<pedal dir="down">` are apparently dropped once there is another `<pedal dir="down">`, so only the last one is respected. For the endpoint of the line, it apparently picks the first `<pedal dir="up">` in document order that it finds, even though that belongs to staff 1 and is anchored to a different position than the one on staff 4.
* In bar 3, the same behavior (picking the first `<pedal dir="up">` in document order) can be observed in a single-measure context. Pedal elements are intentionally unordered here. The first pedal line should be the shortest one, the last one should be the longest, but it's in reverse because `@staff` is not respected. The intentionally unordered encoding is admittedly quirky, but it's still valid.
* In bar 4, there are multiple pedal lines in one bar, but again intentionally unordered to demonstrate the problem.

```xml
<mei xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title/>
   </titleStmt>
   <pubStmt/>
  </fileDesc>
 </meiHead>
 <music>
  <body>
   <mdiv>
    <score>
     <scoreDef meter.count="4" meter.unit="4">
      <staffGrp>
       <staffDef clef.shape="G" clef.line="2" lines="5" n="1"/>
       <staffDef clef.shape="G" clef.line="2" lines="5" n="2"/>
       <staffDef clef.shape="G" clef.line="2" lines="5" n="3"/>
       <staffDef clef.shape="G" clef.line="2" lines="5" n="4"/>
      </staffGrp>
     </scoreDef>
     <section>
      <pb></pb>
      <sb/>
      <measure n="1">
       <staff n="1">
        <layer n="1">
         <mRest xml:id="start1"/>
        </layer>        
       </staff>
       <staff n="2">
        <layer n="1">
         <mRest/>
        </layer>
       </staff>
       <staff n="3">
        <layer n="1">
         <mRest/>
        </layer>
       </staff>
       <staff n="4">
        <layer n="1">
         <mRest xml:id="start4"/>
        </layer>
       </staff>
       
       <pedal staff="1" startid="#start1" form="line" dir="down"/>
       <pedal staff="2" tstamp="1" form="line" dir="down"/>
       <pedal staff="3" tstamp="1" form="line" dir="down"/>
       <pedal staff="4" startid="#start4" form="line" dir="down"/>
      </measure>
      <sb/>
      <measure n="2">
       <staff n="1">
        <layer n="1">
         <note pname="g" dur="2" oct="4"/>
         <note pname="g" dur="2" oct="4" xml:id="end1"/>
        </layer>
       </staff>
       <staff n="2">
        <layer n="1">
         <mRest/>
        </layer>
       </staff>
       <staff n="3">
        <layer n="1">
         <note pname="g" dur="2" oct="4"/>
         <note pname="g" dur="2" oct="4" xml:id="end3"/>
        </layer>
       </staff>
       <staff n="4">
        <layer n="1">
         <mRest/>
        </layer>
       </staff>
       <pedal staff="1" startid="#end1" form="line" dir="up" xml:id="pedalend11"/>
       <pedal staff="2" tstamp="4" form="line" dir="up" xml:id="pedalend21"/>
       <pedal staff="3" startid="#end3" form="line" dir="up" xml:id="pedalend31"/>
       <pedal staff="4" tstamp="4" form="line" dir="up" xml:id="pedalend41"/>
      </measure>
      <pb/>
      <measure n="3">
       <staff n="1">
        <layer n="1">
         <note pname="g" dur="4" oct="4" xml:id="start1single"/>
         <note pname="g" dur="2" dots="1" oct="4" xml:id="end1single"/>
        </layer>        
       </staff>
       <staff n="2">
        <layer n="1">
         <mRest/>
        </layer>
       </staff>
       <staff n="3">
        <layer n="1">
         <note pname="g" dur="2" oct="4"/>
         <note pname="g" dur="2" oct="4" xml:id="end3single"/>
        </layer>
       </staff>
       <staff n="4">
        <layer n="1">
         <note pname="g" dur="1" oct="4" xml:id="start4single"/>
        </layer>
       </staff>
       
       <pedal staff="1" startid="#start1single" form="line" dir="down"/>       
       
       <pedal staff="4" dir="up" tstamp="3.5" form="line" xml:id="pedalend43"/>
       
       <pedal staff="2" tstamp="1" form="line" dir="down"/>

       <pedal staff="3" dir="up" startid="#end3single" form="line" xml:id="pedalend33"/>
       
       <pedal staff="3" tstamp="1" form="line" dir="down"/>

       <pedal staff="2" dir="up" tstamp="2.5" form="line" xml:id="pedalend23"/>

       <pedal staff="4" startid="#start4single" form="line" dir="down"/>

       <pedal staff="1" dir="up" startid="#end1single" form="line" xml:id="pedalend13"/>
      </measure>
      <measure n="4">
       <staff n="1">
        <layer n="1">
         <note pname="g" dur="2" dots="1" oct="4" xml:id="start14"/>
         <note pname="g" dur="4" oct="4" xml:id="end14"/>
        </layer>        
       </staff>
       <staff n="2">
        <layer n="1">
         <mRest/>
        </layer>
       </staff>
       <staff n="3">
        <layer n="1">
         <mRest/>
        </layer>
       </staff>
       <staff n="4">
        <layer n="1">
         <mRest/>
        </layer>
       </staff>
       
       <pedal staff="1" startid="#start14" form="line" dir="down"/>       
       <pedal staff="1" tstamp="3" form="line" dir="down"/>
       
       <pedal staff="1" dir="up" tstamp="2.5" form="line" xml:id="pedalend14a"/>
       <pedal staff="1" dir="up" startid="#end14" form="line" xml:id="pedalend14b"/>
       </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

### LINKED ISSUE #1582: Pedal lines must continue over system breaks
Piano pedal lines stop at the end of a system:

grafik

They should continue to the same point as without system breaks:

grafik

```xml
<?xml version="1.0" encoding="UTF-8"?>
<mei xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title/>
   </titleStmt>
   <pubStmt/>
  </fileDesc>
 </meiHead>
 <music>
  <body>
   <mdiv>
    <score>
     <scoreDef meter.count="4" meter.unit="4">
      <staffGrp>
       <staffDef clef.shape="G" clef.line="2" lines="5" n="1"/>
      </staffGrp>
     </scoreDef>
     <section>
      <pb/>
      <sb/>
      <measure n="1">
       <staff n="1">
        <layer n="1">
         <mRest xml:id="start1"/>
        </layer>
       </staff>
       <dir tstamp="1" place="above">only IDs</dir>
       <pedal staff="1" tstamp="1" form="line" dir="down"/>
      </measure>
      <sb/>
      <measure n="2">
       <staff n="1">
        <layer n="1">
         <note pname="g" dur="2" oct="4"/>
         <note pname="g" dur="2" oct="4" xml:id="end2"/>
        </layer>
       </staff>
       <pedal staff="1" dir="up" startid="#end2" form="line"/>
      </measure>
      <sb/>
      <measure n="3">
       <staff n="1">
        <layer n="1">
         <mRest/>
        </layer>
       </staff>
       <dir tstamp="1" place="above">only timestamps</dir>
       <pedal staff="1" tstamp="1" form="line" dir="down"/>
      </measure>
      <sb/>
      <measure n="4">
       <staff n="1">
        <layer>
         <mRest/>
        </layer>
       </staff>
       <pedal staff="1" dir="up" tstamp="3" form="line"/>
      </measure>
      <sb/>
      <measure n="5">
       <staff n="1">
        <layer n="1">
         <mRest/>
        </layer>
       </staff>
       <dir tstamp="1" place="above">start with timestamps, end with IDs</dir>
       <pedal staff="1" tstamp="1" form="line" dir="down"/>
      </measure>
      <sb/>
      <measure n="6">
       <staff n="1">
        <layer>
         <mRest xml:id="end6"/>
        </layer>
       </staff>
       <pedal staff="1" dir="up" startid="#end6" form="line"/>
      </measure>
      <sb/>
      <measure n="7">
       <staff n="1">
        <layer n="1">
         <note pname="g" dur="2" oct="4"/>
         <note pname="g" dur="2" oct="4" xml:id="start7"/>
        </layer>
       </staff>
       <dir tstamp="1" place="above">start with IDs, end with timestamps</dir>
       <pedal staff="1" startid="#start7" form="line" dir="down"/>
      </measure>
      <sb/>
      <measure n="8">
       <staff n="1">
        <layer n="1">
         <mRest/>
        </layer>
       </staff>
       <pedal staff="1" dir="up" tstamp="3" form="line"/>
      </measure>
      <sb/>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

### PR DESCRIPTION
**Pull request by rettinghaus**
closes #1575
closes #1582

### CODE REVIEW

**Comment by lpugin** [comment]
A few things before I review this PR:
* can we have it without all the formatting changes that are un-related? It makes it difficult to review.
* encoding of pedal lines with simply up and down is quite poor. There was a discussion here a while ago on this topic https://github.com/music-encoding/music-encoding/issues/305. It think it would makes sense to use either `@tstamp2`/`@endid` or `@next`. This would avoid un-resolved cases
* can we have the images of the desired rendering for #1575?

**Comment by rettinghaus** [comment]
Removed the clang-format. Should be run after merge.

**Comment by lpugin** [comment]
Since this PR is about the simple cases (down / up) it should implement the @tstamp2` (or `@endid`) approach recommended here music-encoding/guidelines#138

(We can then treat bounces with the @next as suggested here music-encoding/music-encoding#305)

OK?

**Comment by rettinghaus** [comment]
Still, the main goal is to have Ped. glyphs interchangeable with line rendering. 

Also, I would expect an encoding with `@tstamp2` to produce something similar as with `dir` or `dynam`, i.e. 
pedal preview

But this still is undefined, see https://github.com/music-encoding/music-encoding/issues/644

**Comment by lpugin** [comment]
@rettinghaus I am closing it and you can make a fresh PR implementing support for the new MEI attribute.

**Comment by rettinghaus** [comment]
The PR had nothing to do with the new pedal-style value. It was about connecting single `<pedal>` elements, because you cannot have bounces with `@tstamp2`.

**Pull request closed without merging**
