### PR TITLE
Rendering portato slurs

### PR DESCRIPTION
**Pull request by DavidBauer1984**
This PR improves the rendering of portato slurs. Works with stem side or centered staccato as well as with other articulations.

| Before | After |
| ------ | ----- |
| Before1 | Example1 |
| Before2 | Example2 |
| Before3 | Example3 |

<details>
  <summary>Show MEI example</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title />
            <respStmt />
         </titleStmt>
         <pubStmt><date isodate="2021-07-30" type="encoding-date">2021-07-30</date>
         </pubStmt>
      </fileDesc>
      <encodingDesc xml:id="encodingdesc-xwopln">
         <appInfo xml:id="appinfo-a209u3">
            <application xml:id="application-oqlg5f" isodate="2021-10-07T15:48:50" version="3.7.0-dev-ab9a2ad">
               <name xml:id="name-54q3e8">Verovio</name>
               <p xml:id="p-9bogng">Transcoded from MusicXML</p>
            </application>
         </appInfo>
      </encodingDesc>
   </meiHead>
   <music>
      <body>
         <mdiv xml:id="mlj4v68">
            <score xml:id="sdie2kd">
               <scoreDef xml:id="sqosio4">
                  <staffGrp xml:id="s2kukk6">
                     <staffGrp xml:id="S1-ty9q8jPDVsCWNSEmZ4EMBA" bar.thru="true">
                        <staffDef xml:id="sbx4ten" n="1" lines="5" ppq="4">
                           <clef xml:id="clef-1" shape="G" line="2" />
                           <keySig xml:id="key-1" sig="2f" />
                           <meterSig xml:id="time-1" count="4" sym="common" unit="4" />
                        </staffDef>
                        <staffDef xml:id="spk2jp7" n="2" lines="5" ppq="4">
                           <clef xml:id="clef-2" shape="F" line="4" />
                           <keySig xml:id="key-2" sig="2f" />
                           <meterSig xml:id="time-2" count="4" sym="common" unit="4" />
                        </staffDef>
                        <grpSym xml:id="gn2ijqh" symbol="brace" />
                     </staffGrp>
                  </staffGrp>
               </scoreDef>
               <section xml:id="svuhz75">
                  <pb xml:id="py6q87o" />
                  <measure xml:id="measure-0006-11020-10920-1-mdiv-1" n="13">
                     <staff xml:id="smgu9ou" n="1">
                        <layer xml:id="lawwt1f" n="1">
                           <note xml:id="note-0006-11060-11050-1" dots="1" dur.ppq="12" dur="2" oct="4" pname="g" stem.dir="up" />
                           <note xml:id="note-0006-11260-10990-1" dots="1" dur.ppq="12" dur="2" oct="5" pname="g" stem.dir="up" />
                        </layer>
                        <layer xml:id="lgm9mkr" n="2">
                           <rest xml:id="rest-0006-11070-11120" dur.ppq="4" dur="4" />
                           <chord xml:id="co7zcdo" dur.ppq="4" dur="4" stem.dir="down">
                              <artic xml:id="abas6oy" artic="stacc" place="below" />
                              <note xml:id="note-0006-11130-11080-2" oct="4" pname="d" />
                              <note xml:id="note-0006-11130-11090-2" oct="3" pname="b" accid.ges="f" />
                           </chord>
                           <note xml:id="note-0006-11200-11080-2" dur.ppq="4" dur="4" oct="4" pname="c" stem.dir="down">
                              <artic xml:id="arny5z0" artic="stacc" place="below" />
                           </note>
                           <rest xml:id="rest-0006-11270-11080" dur.ppq="4" dur="4" />
                           <chord xml:id="cyiejwb" dur.ppq="4" dur="4" stem.dir="down">
                              <artic xml:id="arcvmfc" artic="stacc" place="below" />
                              <note xml:id="note-0006-11330-11020-2" oct="5" pname="d">
                                 <accid xml:id="a129g6r" accid="f" accid.ges="f" />
                              </note>
                              <note xml:id="note-0006-11330-11030-2" oct="4" pname="b" accid.ges="f" />
                              <note xml:id="note-0006-11330-11050-2" oct="4" pname="g" />
                           </chord>
                           <chord xml:id="chi0avh" dur.ppq="4" dur="4" stem.dir="down">
                              <artic xml:id="arcvmfd" artic="stacc" place="below" />
                              <note xml:id="note-0006-11400-11020-2" oct="5" pname="d" accid.ges="f" />
                              <note xml:id="note-0006-11400-11030-2" oct="4" pname="b" accid.ges="f" />
                              <note xml:id="note-0006-11400-11050-2" oct="4" pname="g" />
                           </chord>
                        </layer>
                     </staff>
                     <staff xml:id="sg0qc6i" n="2">
                        <layer xml:id="lqfgtco" n="5">
                           <rest xml:id="rest-0006-11070-11260" dur.ppq="4" dur="4" />
                           <note xml:id="note-0006-11130-11270-1" dur.ppq="4" dur="4" oct="2" pname="g" stem.dir="up">
                              <artic xml:id="am2q1ou" artic="stacc" place="below" />
                           </note>
                           <note xml:id="note-0006-11200-11270-1" dur.ppq="4" dur="4" oct="2" pname="g" stem.dir="up">
                              <artic xml:id="arw4ykl" artic="stacc" place="below" />
                           </note>
                           <rest xml:id="rest-0006-11270-11260" dur.ppq="4" dur="4" />
                           <note xml:id="note-0006-11330-11170-2" dur.ppq="4" dur="4" oct="4" pname="e" stem.dir="down">
                              <accid xml:id="ayxcu0h" accid="n" accid.ges="n" />
                              <artic xml:id="aiq1w51" artic="stacc" place="above" />
                           </note>
                           <note xml:id="note-0006-11400-11170-2" dur.ppq="4" dur="4" oct="4" pname="e" stem.dir="down" accid.ges="n">
                              <artic xml:id="afbbodv" artic="stacc" place="above" />
                           </note>
                        </layer>
                     </staff>
                     <slur xml:id="bow-0006-11350-10920" startid="#note-0006-11260-10990-1" endid="#note-0006-9540-11480-1" curvedir="above" />
                     <slur xml:id="bow-0006-11160-11160" startid="#note-0006-11130-11080-2" endid="#note-0006-11200-11080-2" curvedir="below" />
                     <slur xml:id="bow-0006-11360-11120" startid="#note-0006-11330-11030-2" endid="#note-0006-11400-11050-2" curvedir="below" />
                     <slur xml:id="bow-0006-11160-11300" startid="#note-0006-11130-11270-1" endid="#note-0006-11200-11270-1" />
                     <slur xml:id="bow-0006-11360-11140" startid="#note-0006-11330-11170-2" endid="#note-0006-11400-11170-2" />
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```
</details>

### CODE REVIEW

**Comment by lpugin** [comment]
Does it close this one https://github.com/rism-digital/verovio/issues/410 ?

**Comment by rettinghaus** [comment]
I would say so. @craigsapp?

**Comment by craigsapp** [comment]
I looks like it will.  How do you test a pull request in a local computer?  I  tried the instructions on this page:

```
git clone https://github.com/eNote-GmbH/verovio.git
cd verovio
git checkout -b eNote-GmbH-develop-portatoSlur develop
git pull https://github.com/eNote-GmbH/verovio.git develop-portatoSlur
```

But there are merge conflicts:

```
From https://github.com/eNote-GmbH/verovio
 * branch                develop-portatoSlur -> FETCH_HEAD
Auto-merging tools/main.cpp
Auto-merging src/vrv.cpp
Auto-merging src/toolkit.cpp
Auto-merging src/options.cpp
CONFLICT (content): Merge conflict in src/options.cpp
Auto-merging include/vrv/vrv.h
CONFLICT (content): Merge conflict in include/vrv/vrv.h
Auto-merging include/vrv/options.h
CONFLICT (content): Merge conflict in include/vrv/options.h
error: could not apply 311391b0f... Introduced option --text-font
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 311391b0f... Introduced option --text-font
```

**Comment by rettinghaus** [comment]
@craigsapp looks like you're trying to rebase from our develop branch, which will not work.

**Comment by DavidBauer1984** [comment]
@craigsapp What about
`git clone -b develop-portatoSlur https://github.com/eNote-GmbH/verovio`
and you should be ready to go.

**Comment by lpugin** [comment]
Could you check the artic-007 test?

image

**Comment by DavidBauer1984** [comment]
There seem to be different styles:
(A) Drawing portato slurs from dot to dot
(B) Starting portato slurs horizontally before the dot and ending them after the dot.

An example where (A) is exclusively used is the following print:
PrintEdition

In the implementation we mostly use style (B), but use (A) for stem side staccato when the slur is on the stem side. I don't really like slurs which are asymmetric with respect to the dots
Asymmetric

Thus for stem side staccato rendering I see three options:
(1) Always use style (A).
(2) Always use style (B).
(3) Use style (A) for slurs on the stem side and style (B) for slurs on the notehead side.

The current implementation uses (3). Note that (2) would imply for slurs on the stem side that the slur starts left of its start note/chord and ends right of its end note/chord. Was a bit unsure if this has any negative consequences on adjustment, but we might try it out. Please discuss which option you prefer!

**Comment by craigsapp** [comment]
I prefer style A, but would not object to style B.   Style A as in the example print aligns the staccatos with the endpoints of the slurs, and probably some editors do not like that (since the staccatos may tend to look like broken pieces of the slur).  Verovio is currently not doing that form of Style A, so it is a clearer form of style A compared to the example print.

Style A+B mixture gets complicated in terms of cases where they are close together:

Screen Shot 2021-11-09 at 3 05 34 AM

Perhaps a modified form of Style B would be better than Style A+B:   When the stem-side staccatos are centered on the stem, Style A is used on both side of the notehead: slurs are centered on staccatos.  When the stem-side staccatos are centered on the notehead, then style B is used on both sides fo the notehead.  But this will still be complicated by the example @lpugin just posted:

Screen Shot 2021-11-09 at 3 11 53 AM

The second slur should more properly be the same style as the third slur.

Portato slurs are more commonly having all of the notes under the slur with the same pitch (so the above is not a common case).   Probably when there is a melodic change it should behave more like standard slurs; otherwise mixing portato slurs and regular slurs with difference styles will be distracting.  But having a different style for horizontal portato slurs compare to non-horizontal slurs would probably work.

<details>
<summary>
Click to view MEI data for above example.
</summary>

```mei
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2021-11-09T03:15:46" version="3.7.0-dev-370ff5f">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
  <extMeta>
   <frames xmlns="http://www.humdrum.org/ns/humxml">
    <metaFrame n="12" token="!!!RDF**kern: > = above" xml:id="L13">
     <frameInfo>
      <startTime float="3" />
      <frameType>reference</frameType>
      <referenceKey>RDF**kern</referenceKey>
      <referenceValue>&gt; = above</referenceValue>
     </frameInfo>
    </metaFrame>
   </frames>
  </extMeta>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mg3i004">
    <score xml:id="sot2msd">
     <scoreDef xml:id="sp7mxom">
      <staffGrp xml:id="sknqhsg">
       <staffDef xml:id="srgvsbd" n="1" lines="5">
        <clef xml:id="clef-L2F1" shape="G" line="2" />
        <meterSig xml:id="metersig-L3F1" count="2" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1">
       <staff xml:id="sffpl2u" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <beam xml:id="beam-L5F1-L6F1">
          <note xml:id="note-L5F1" dur="8" oct="4" pname="f" accid.ges="n">
           <artic xml:id="artic-L5F1" artic="stacc" />
          </note>
          <note xml:id="note-L6F1" dur="8" oct="4" pname="g" accid.ges="n">
           <artic xml:id="artic-L6F1" artic="stacc" />
          </note>
         </beam>
         <beam xml:id="beam-L7F1-L8F1">
          <note xml:id="note-L7F1" dur="8" oct="4" pname="f" accid.ges="n">
           <artic xml:id="artic-L7F1" artic="stacc" place="above" />
          </note>
          <note xml:id="note-L8F1" dur="8" oct="4" pname="g" accid.ges="n">
           <artic xml:id="artic-L8F1" artic="stacc" place="above" />
          </note>
         </beam>
         <beam xml:id="beam-L9F1-L10F1">
          <note xml:id="note-L9F1" dur="8" oct="4" pname="f" accid.ges="n" />
          <note xml:id="note-L10F1" dur="8" oct="4" pname="g" accid.ges="n" />
         </beam>
        </layer>
       </staff>
       <slur xml:id="slur-L5F1-L6F1" staff="1" startid="#note-L5F1" endid="#note-L6F1" />
       <slur xml:id="slur-L7F1-L8F1" staff="1" startid="#note-L7F1" endid="#note-L8F1" />
       <slur xml:id="slur-L9F1-L10F1" staff="1" startid="#note-L9F1" endid="#note-L10F1" />
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

**Comment by DavidBauer1984** [comment]
- We now consistently use style (A), I have updated the renderings in the PR.
- Artic-007 should now look better. However, as @rettinghaus explained to me, the cases with beams and staccati on opposite sites do not really make sense from a musicology point of view.
Example4

- I fixed another problem with portato slurs starting/ending at chords with adjacent notes.
Example5

**Comment by craigsapp** [comment]
Looks great!

> the cases with beams and staccati on opposite sites do not really make sense from a musicology point of view.

Yes, I can't imagine a case where that would happen, especially for stringed instruments.

A general observation is that the slurs seem a little too far away from the staccatos:

Screen Shot 2021-11-15 at 3 22 21 AM

And in general the staccatos are too close to the beam when on the stem sides of the notes (and mentioned previously also when on the notehead size when the note its outside of the staff).  The problem is that they are visually merging with the beams slightly since they are so close.

The non-cue staccato size makes them less confused with the stem as well since they are thicker than the stem width now, and I am not concerned with the stem-side spacings in this case:

Screen Shot 2021-11-15 at 3 23 56 AM

But it would be nice to have them centered vertically in the space between the slur and the stem (by bringing the slur closer to the staccatos.

**Comment by DavidBauer1984** [comment]
We actually place the slur endpoints on the staccati and let the slur adjustment machinery do its work to vertically displace the slur. The latter does not really know about portato slurs, so it would be rather complicated to gain fine control over the displacement between the slur and the staccato (i.e. bringing the slur closer to the staccatos). Hopefully the rendering is fine for now and we could focus on this fine tuning later in a separate issue / PR.

**Pull request merged**
