### PR TITLE
Add option to select elision glyph

### PR DESCRIPTION
**Pull request by lpugin**
The PR adds the option `--lyric-elision` 
```bash
 --lyric-elision <s>            The lyric elision width (default: "regular"; other values: "narrow", "wide", "unicode")
```

Example with Bravura:

`regular`
image

`narrow`
image

`wide`
image

<details>
<summary>MEI</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title />
            <respStmt />
         </titleStmt>
         <pubStmt></pubStmt>
      </fileDesc>
      <encodingDesc xml:id="encodingdesc-0000001524618759">
         <appInfo xml:id="appinfo-0000000492606509">
            <application xml:id="application-0000000688137578" isodate="2020-03-06T10:57:54" version="2.6.0-dev-71070ce">
               <name xml:id="name-0000001328834351">Verovio</name>
               <p xml:id="p-0000002036492104">Transcoded from MusicXML</p>
            </application>
         </appInfo>
      </encodingDesc>
   </meiHead>
   <music>
      <body>
         <mdiv xml:id="mdiv-0000000728426042">
            <score xml:id="score-0000001999699994">
               <scoreDef xml:id="scoredef-0000002076790294" midi.bpm="121">
                  <staffGrp xml:id="staffgrp-0000000557864736">
                     <staffDef xml:id="staffdef-0000001259557467" n="1" lines="5" ppq="2" clef.shape="G" clef.line="2" meter.count="4" meter.unit="4" meter.sym="common">
                        <keySig xml:id="keysig-0000000231478358" mode="major" sig="2f" />
                        <instrDef xml:id="instrdef-0000000119015150" midi.channel="0" midi.instrnum="48" midi.volume="80.00%" />
                     </staffDef>
                  </staffGrp>
               </scoreDef>
               <section xml:id="section-0000000838723608">
                  <pb xml:id="pb-0000000345020748" />
                  <measure xml:id="measure-0000000460274445" n="1">
                     <staff xml:id="staff-0000000401453663" n="1">
                        <layer xml:id="layer-0000001985578814" n="1">
                           <rest xml:id="rest-0000001874736165" dur.ppq="2" dur="4" />
                           <note xml:id="note-0000000810656371" dur.ppq="1" dur="8" oct="4" pname="d" stem.dir="up">
                              <verse xml:id="verse-0000001065370829" n="1">
                                 <syl xml:id="syl-0000002116357964" con="b">De</syl>
                                 <syl xml:id="syl-0000001081761921" con="s">a</syl>
                              </verse>
                           </note>
                           <note xml:id="note-0000000828590539" dur.ppq="1" dur="8" oct="4" pname="d" stem.dir="up">
                              <verse xml:id="verse-0000001837221825" n="1">
                                 <syl xml:id="syl-0000001667336209" con="s" wordpos="t">quel</syl>
                              </verse>
                           </note>
                           <note xml:id="note-0000000049117142" dur.ppq="2" dur="4" oct="4" pname="g" stem.dir="up">
                              <verse xml:id="verse-0000000878085146" n="1">
                                 <syl xml:id="syl-0000000469426638" con="d" wordpos="i">mu</syl>
                              </verse>
                           </note>
                           <note xml:id="note-0000001413050235" dur.ppq="1" dur="8" oct="4" pname="g" stem.dir="up">
                              <verse xml:id="verse-0000000113647472" n="1">
                                 <syl xml:id="syl-0000000960099721" con="b">ro</syl>
                                 <syl xml:id="syl-0000001497249258" con="s" wordpos="t">en</syl>
                              </verse>
                           </note>
                           <note xml:id="note-0000001495329057" dur.ppq="1" dur="8" oct="4" pname="a" stem.dir="up">
                              <verse xml:id="verse-0000002141823805" n="1">
                                 <syl xml:id="syl-0000001511799621" con="s">la</syl>
                              </verse>
                           </note>
                        </layer>
                     </staff>
                  </measure>
                  <measure xml:id="measure-0000000562677263" n="2">
                     <staff xml:id="staff-0000000863035375" n="1">
                        <layer xml:id="layer-0000000930995787" n="1">
                           <note xml:id="note-0000000680340067" dur.ppq="1" dur="8" oct="4" pname="b" stem.dir="down" accid.ges="f">
                              <verse xml:id="verse-0000001284954414" n="1">
                                 <syl xml:id="syl-0000001133281866" con="d" wordpos="i">rui</syl>
                              </verse>
                           </note>
                           <note xml:id="note-0000002139752951" dur.ppq="1" dur="8" oct="4" pname="b" stem.dir="down" accid.ges="f">
                              <verse xml:id="verse-0000000745934409" n="1">
                                 <syl xml:id="syl-0000002057564524" con="s" wordpos="t">na</syl>
                              </verse>
                           </note>
                           <rest xml:id="rest-0000000963805034" dur.ppq="1" dur="8" />
                           <note xml:id="note-0000000202057117" dur.ppq="1" dur="8" oct="5" pname="d" stem.dir="down">
                              <verse xml:id="verse-0000000802319512" n="1">
                                 <syl xml:id="syl-0000000534218671" con="d" wordpos="i">re</syl>
                              </verse>
                           </note>
                           <note xml:id="note-0000000790535605" dur.ppq="1" dur="8" oct="4" pname="b" stem.dir="down" accid.ges="f">
                              <verse xml:id="verse-0000001997416957" n="1">
                                 <syl xml:id="syl-0000001122426395" con="d" wordpos="m">pa</syl>
                              </verse>
                           </note>
                           <note xml:id="note-0000000755501560" dur.ppq="1" dur="8" oct="4" pname="b" stem.dir="down" accid.ges="f">
                              <verse xml:id="verse-0000000303034852" n="1">
                                 <syl xml:id="syl-0000001423030527" con="s" wordpos="t">ra</syl>
                              </verse>
                           </note>
                           <note xml:id="note-0000002108365534" dur.ppq="1" dur="8" oct="4" pname="a" stem.dir="up">
                              <verse xml:id="verse-0000001819354438" n="1">
                                 <syl xml:id="syl-0000002017873480" con="b">mi</syl>
                                 <syl xml:id="syl-0000000669915262" con="s">a</syl>
                              </verse>
                           </note>
                           <note xml:id="note-0000001732653601" dur.ppq="1" dur="8" oct="4" pname="g" stem.dir="up">
                              <verse xml:id="verse-0000000830818687" n="1">
                                 <syl xml:id="syl-0000000630999615" con="d" wordpos="m">ten</syl>
                              </verse>
                           </note>
                        </layer>
                     </staff>
                  </measure>
                  <measure xml:id="measure-0000001452320564" n="3">
                     <staff xml:id="staff-0000000532149639" n="1">
                        <layer xml:id="layer-0000001717076565" n="1">
                           <note xml:id="note-0000001020579569" dur.ppq="2" dur="4" oct="5" pname="c" stem.dir="down">
                              <verse xml:id="verse-0000000928927594" n="1">
                                 <syl xml:id="syl-0000000279958668" con="s" wordpos="t">ción.</syl>
                              </verse>
                           </note>
                           <rest xml:id="rest-0000002062071811" dur.ppq="2" dur="4" />
                           <note xml:id="note-0000001149832191" dur.ppq="1" dur="8" oct="5" pname="e" stem.dir="down" accid.ges="f">
                              <verse xml:id="verse-0000000300541758" n="1">
                                 <syl xml:id="syl-0000000323788962" con="d" wordpos="i">Mi</syl>
                              </verse>
                           </note>
                           <note xml:id="note-0000001904070037" dur.ppq="1" dur="8" oct="5" pname="c" stem.dir="down">
                              <verse xml:id="verse-0000002051287912" n="1">
                                 <syl xml:id="syl-0000000293468046" con="s" wordpos="t">ra,</syl>
                              </verse>
                           </note>
                           <rest xml:id="rest-0000001420639815" dur.ppq="1" dur="8" />
                           <note xml:id="note-0000000970183359" dur.ppq="1" dur="8" oct="4" pname="g" stem.dir="up">
                              <verse xml:id="verse-0000000028383042" n="1">
                                 <syl xml:id="syl-0000000292417260" con="d" wordpos="i">Ri</syl>
                              </verse>
                           </note>
                        </layer>
                     </staff>
                  </measure>
                  <measure xml:id="measure-0000001278365147" right="invis" n="4">
                     <staff xml:id="staff-0000001511597378" n="1">
                        <layer xml:id="layer-0000000685588036" n="1">
                           <note xml:id="note-0000001428354897" dur.ppq="1" dur="8" oct="5" pname="c" stem.dir="down">
                              <verse xml:id="verse-0000001788547713" n="1">
                                 <syl xml:id="syl-0000001792805332" con="d" wordpos="m">se</syl>
                              </verse>
                           </note>
                           <note xml:id="note-0000002024121059" dur.ppq="1" dur="8" oct="5" pname="c" stem.dir="down">
                              <verse xml:id="verse-0000001114186486" n="1">
                                 <syl xml:id="syl-0000000074868362" con="s" wordpos="t">lo,</syl>
                              </verse>
                           </note>
                           <rest xml:id="rest-0000001587810492" dur.ppq="1" dur="8" />
                           <note xml:id="note-0000001699141422" dur.ppq="1" dur="8" oct="4" pname="g" stem.dir="up">
                              <verse xml:id="verse-0000000232341748" n="1">
                                 <syl xml:id="syl-0000000842488390" con="b">que</syl>
                                 <syl xml:id="syl-0000000766430937" con="s">es</syl>
                              </verse>
                           </note>
                           <note xml:id="note-0000000467022703" dur.ppq="1" dur="8" oct="5" pname="c" stem.dir="down">
                              <verse xml:id="verse-0000000197839536" n="1">
                                 <syl xml:id="syl-0000000784395996" con="s">más</syl>
                              </verse>
                           </note>
                           <note xml:id="note-0000000734860046" dur.ppq="1" dur="8" oct="5" pname="c" stem.dir="down">
                              <verse xml:id="verse-0000000614339225" n="1">
                                 <syl xml:id="syl-0000000097979799" con="s">de</syl>
                              </verse>
                           </note>
                           <note xml:id="note-0000000092711189" dur.ppq="1" dur="8" oct="5" pname="d" stem.dir="down">
                              <verse xml:id="verse-0000001271309448" n="1">
                                 <syl xml:id="syl-0000001583088533" con="s">lo</syl>
                              </verse>
                           </note>
                           <note xml:id="note-0000000140939009" dur.ppq="1" dur="8" oct="5" pname="e" stem.dir="down" accid.ges="f">
                              <verse xml:id="verse-0000001088666406" n="1">
                                 <syl xml:id="syl-0000000655613202" con="s">que</syl>
                              </verse>
                           </note>
                        </layer>
                     </staff>
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```
</details>

### CODE REVIEW

**Comment by rettinghaus** [comment]
Maybe it would be good to have the "normal" undertie (https://unicode-table.com/en/203F/) from the used text font as an another option available? I don't know if it is available in Times though.

**Comment by lpugin** [comment]
Yes, we could add that. This is how it would look like

image

The advantage is that no smufl text font would be needed with it.

**Comment by lpugin** [comment]
`unicode`

image

**Review by rettinghaus — APPROVED** [review]
Looks great, thank you.

**Comment by craigsapp** [comment]
The unicode option is great, since that one will typically match the text font more so than the music font (consider Petaluma for example).

**Pull request merged**
