### PR TITLE
Option for compound dynamics glyph usage

### PR DESCRIPTION
**Pull request by rettinghaus**
This PR adds another option to switch from using SMuFL's pre-defined compound dynamics glyphs to using single glyphs for rendering.

### CODE REVIEW

**Comment by lpugin** [comment]
Could you add a couple of examples? Thanks

**Comment by rettinghaus** [comment]
With `dynam-001.mei` from the test suite Verovio normally produces this: 

dynam-001-compound-glyphs

With the new option `--dynam-single-glyphs` it uses the corresponding single dynamic glyphs for f, m, p, r, s, and z. The result looks almost the same: 

dynam-001-single-glyphs

But in the SVG we now have single entities:

```xml
<g id="d1t8wmsc" class="dynam">
    <use xlink:href="#E524-1uoe3tk" x="6396" y="1803" height="720px" width="720px" />
    <use xlink:href="#E522-1uoe3tk" x="6535" y="1803" height="720px" width="720px" />
    <use xlink:href="#E525-1uoe3tk" x="6702" y="1803" height="720px" width="720px" />
 </g>
```

E.g., allowing coloring of each entity with CSS: 

dynam-001-single-glyphs

**Comment by lpugin** [comment]
Great, thanks. I suspect this will not work with Bravura because of how the advance is set - unless this has changed since last time I looked at it.

**Comment by rettinghaus** [comment]
Indeed, Bravura and Leland do not really work, especially the spacing in forte is bad:  
image
image

**Comment by craigsapp** [comment]
You could have an advance correction applied to Bravura and Leland, and change that correction to zero when fixed in Bravura and Leland.  I thought a recent version of Leland fixed this problem in the font metrics?

**Comment by lpugin** [comment]
Eventually I think Bravura should be fixed. If we correct it, it will remain unnoticed, so it might be counter-productive.

**Pull request merged**
