### PR TITLE
Develop tab update

### PR DESCRIPTION
**Pull request by lpugin**
Integrates
* MIDI output for tablature
* Beam (WIP) support for tablature
* MusicXML import for tablature

### CODE REVIEW

**Comment by lpugin** [comment]
@paul-bayleaf It seems that we have a conflict in the MusicXML importer. How do you want to proceed?

**Comment by paul-bayleaf** [comment]
There are two conflicts in iomusxml.cpp lines 2554 and 2693.  In both the code from develop-tab should replace that in develop.  I don't know how to make this change to fix your merge.

**Comment by lpugin** [comment]
I should have resolved the conflict. Looking at the test suite result, I can see this

Before:
image

After:
image

It is looking pretty promising! If possible I would prefer not to wait too long and merge it before we have other conflicts arising. @rettinghaus @DavidBauer1984 @Monceber ?

**Comment by rettinghaus** [comment]
@lpugin looks good from our side! Please go ahead.

**Pull request merged**
